// en.js: all the app's texts in English.
//
// Every text has a key (e.g. 'tray.salir'), the same ones used in es.js. Pieces in braces, such as {hoy}, are
// replaced with values when the text is shown, so they must be kept exactly as they are.

module.exports = {
  // ----- Language data -----
  'meta.nombre': 'English',
  'meta.locale': 'en-US',          // used to write numbers (12.5) and day names
  'meta.csvSeparador': ',',        // English-language Excel separates columns with commas

  // ----- General -----
  'app.nombre': 'Cupo',
  'hoy.etiqueta': 'Today',
  'sesion.etiqueta': 'Session 5 h',
  'semana.etiqueta': 'Week',
  'reinicio.prefijo': 'Resets: ',
  'hoy.de': '{hoy}% of {limite}%',
  'lectura.cargando': 'Reading usage…',
  'sesion.sinActividad': 'no activity',

  // ----- Errors while reading usage -----
  'error.sinConexion': "Can't reach claude.ai",
  'error.formato': 'claude.ai data changed',
  'error.generico': "Couldn't read usage",

  // ----- Sign in -----
  'login.sinSesion': "You're not signed in",
  'login.expirada': 'Your session expired',
  'login.iniciar': 'Sign in',
  'login.reentrar': 'Sign in again',
  'login.titulo': 'Sign in to Claude',

  // ----- Panels -----
  'panel.historial': 'History',
  'panel.desglose': 'Weekly breakdown',
  'panel.proyeccion': 'Projection',
  'panel.ajustes': 'Settings',
  'panel.detalle': 'Details',
  'panel.cerrar': 'Close',
  'panel.cerrarAria': 'Close the panel',

  // ----- Card buttons -----
  'boton.historial': 'Usage history',
  'boton.historialAria': 'View the usage history',
  'boton.desglose': 'Weekly breakdown by product',
  'boton.desgloseAria': 'View the weekly breakdown by product',
  'boton.proyeccion': 'Projection: at this pace...',
  'boton.proyeccionAria': 'View the usage projection',
  'boton.ajustes': 'Settings',
  'boton.ajustesAria': 'Open settings',
  'boton.compacto': 'Compact view (one line)',
  'boton.compactoAria': 'Switch between the compact and the normal view',
  'boton.completo': 'Full view (everything at once)',
  'boton.completoAria': 'Switch between the full and the normal view',
  'boton.orientacion': 'Change the layout (vertical / horizontal)',
  'boton.orientacionAria': 'Switch between the vertical and the horizontal layout',

  // ----- History -----
  'historial.hoy': 'today',
  'historial.limiteDia': "That day's limit: {limite}%",

  // ----- Product names (the breakdown) -----
  'producto.claude_code': 'Claude Code',
  'producto.chat': 'Chats',
  'producto.cowork': 'Cowork',
  'producto.other': 'Other',

  // ----- Breakdown -----
  'desglose.sinDatos': 'No data yet. Wait for the first reading.',
  'desglose.sinDesglose': "claude.ai didn't provide the breakdown in this reading.",
  'desglose.nota': 'Split of what you used this week ({semana}% of your quota).',

  // ----- Projection -----
  'proy.dia.yaLlegaste': "You've already hit today's limit",
  'proy.dia.yaLlegaste.detalle': 'Better take it easy for the rest of the day.',
  'proy.dia.llegaras': "You'd hit your limit around {hora}",
  'proy.dia.llegaras.detalle': 'At this pace, before midnight.',
  'proy.dia.noLlegaras': "You wouldn't hit your limit today",
  'proy.dia.noLlegaras.detalle': "You'd end the day at ~{fin}%.",
  'proy.dia.sinUso': "You haven't used anything yet today",
  'proy.dia.sinUso.detalle': "At this pace you wouldn't reach the limit.",
  'proy.dia.sinDatos': "It's too early to estimate",
  'proy.dia.sinDatos.detalle': 'We need at least half an hour of measuring.',
  'proy.semana.yaLlegaste': "You've used up your weekly quota",
  'proy.semana.yaLlegaste.detalle': 'It resets {reinicio}.',
  'proy.semana.llegaras': "You'd reach 100% on {cuando}",
  'proy.semana.llegaras.detalle': 'Before the reset ({reinicio}).',
  'proy.semana.noLlegaras': "You wouldn't use up your quota this week",
  'proy.semana.noLlegaras.detalle': "You'd reach ~{fin}% before the reset.",
  'proy.semana.sinUso': "You haven't used anything yet this week",
  'proy.semana.sinUso.detalle': 'Nothing to project yet.',
  'proy.semana.sinDatos': "It's too early to estimate",
  'proy.semana.sinDatos.detalle': 'The week has just started.',
  'proy.sinDatos': 'No data yet',
  'proy.sinDatos.detalle': 'Wait for the first reading.',
  'proy.nota': 'Estimates based on your usage pace so far.',

  // ----- Settings -----
  'aj.seccion.vista': 'View',
  'aj.vista': 'View',
  'aj.vista.normal': 'Normal',
  'aj.vista.compacto': 'Compact (single line)',
  'aj.vista.completo': 'Full (everything at once)',
  'aj.disposicion': 'Layout',
  'aj.disposicion.vertical': 'Vertical (stacked bars)',
  'aj.disposicion.horizontal': 'Horizontal (side by side)',
  'aj.disposicion.ayuda': 'Applies to the normal view; the full view is always wide.',
  'aj.seccion.escala': 'Interface scale',
  'aj.escala.rapidos': 'Quick sizes',
  'aj.escala.ayuda': 'Makes everything bigger or smaller instantly. Also: Ctrl + mouse wheel (Ctrl 0 returns to 100%).',
  'aj.seccion.apariencia': 'Appearance',
  'aj.tema': 'Theme',
  'aj.tema.oscuro': 'Dark',
  'aj.tema.claro': 'Light',
  'aj.tema.auto': 'Automatic (like Windows)',
  'aj.transparencia': 'Background transparency',
  'aj.siempreEncima': 'Always on top of other windows',
  'aj.idioma': 'Language',
  'aj.idioma.auto': 'Automatic (like Windows)',
  'aj.seccion.limite': 'Daily limit',
  'aj.limite': 'Limit',
  'aj.aviso': 'Early warning',
  'aj.limite.ayuda': 'How much of your weekly quota you want to use at most per day. The warning must be lower than the limit.',
  'aj.limitesPorDia': 'A different limit for each day',
  'aj.limitesPorDia.ayuda': 'The early warning adjusts itself, in the same proportion.',
  'aj.dia.0': 'Mo',
  'aj.dia.1': 'Tu',
  'aj.dia.2': 'We',
  'aj.dia.3': 'Th',
  'aj.dia.4': 'Fr',
  'aj.dia.5': 'Sa',
  'aj.dia.6': 'Su',
  'aj.dia.aria': 'Limit for {dia}',
  'aj.seccion.sesion': '5-hour session',
  'aj.sesion.aviso': 'Warn me when it reaches',
  'aj.sesion.activar': 'Turn on session alerts',
  'aj.seccion.consulta': 'Refresh',
  'aj.intervalo': 'Check usage every',
  'aj.intervalo.minutos': '{n} minutes',
  'aj.intervalo.hora': '1 hour',
  'aj.intervalo.ayuda': 'The minimum is 5 minutes.',
  'aj.seccion.sistema': 'System and data',
  'aj.arranque': 'Open the widget when Windows starts',
  'aj.exportar': 'Export history (CSV)…',
  'aj.guardar': 'Save',
  'aj.guardado': 'Saved ✓',
  'aj.exportado': 'Done: {n} day(s) saved.',

  // ----- Settings validation errors -----
  'err.limite': 'The daily limit must be between 1% and 100%.',
  'err.avisoMinimo': 'The early warning must be at least 1%.',
  'err.avisoMenor': 'The early warning must be lower than the daily limit.',
  'err.intervalo': 'The refresh interval is not valid.',
  'err.umbralSesion': 'The 5-hour session warning must be between 50% and 99%.',
  'err.opcion': 'An option has an invalid value.',
  'err.vista': 'The selected view is not valid.',
  'err.disposicion': 'The selected layout is not valid.',
  'err.tema': 'The selected theme is not valid.',
  'err.idioma': 'The selected language is not valid.',
  'err.transparencia': 'The transparency must leave the widget between 40% and 100% visible.',
  'err.escala': 'The scale must be between {min}% and {max}%.',
  'err.limitesSiete': 'The per-day limits must be seven values, Monday to Sunday.',
  'err.limiteDia': "Each day's limit must be between 1% and 100%.",

  // ----- Tray menu (next to the clock) -----
  'tray.actualizado': 'Cupo · updated {hora}',
  'tray.actualizar': 'Refresh',
  'tray.mostrarOcultar': 'Show / Hide',
  'tray.siempreEncima': 'Always on top',
  'tray.historial': 'History',
  'tray.desglose': 'Weekly breakdown',
  'tray.proyeccion': 'Projection',
  'tray.vista': 'View',
  'tray.vista.normal': 'Normal',
  'tray.vista.compacto': 'Compact (one line)',
  'tray.vista.completo': 'Full (everything at once)',
  'tray.disposicion.vertical': 'Vertical layout',
  'tray.disposicion.horizontal': 'Horizontal layout',
  'tray.exportar': 'Export history (CSV)…',
  'tray.ajustes': 'Settings',
  'tray.cerrarSesion': 'Sign out',
  'tray.salir': 'Quit',

  // ----- Exporting the history -----
  'exportar.titulo': 'Export usage history',
  'exportar.filtro': 'CSV file (opens in Excel)',
  'exportar.nombreArchivo': 'claude-usage-history-{fecha}.csv',
  'exportar.vacio': 'There are no recorded days to export yet.',
  'exportar.error': 'Could not save the file: {mensaje}',
  'csv.fecha': 'Date',
  'csv.uso': 'Daily usage (%)',
  'csv.limite': 'Daily limit (%)',
  'csv.supero': 'Exceeded the limit?',
  'csv.si': 'Yes',
  'csv.no': 'No',

  // ----- Windows notifications -----
  'alerta.limite.titulo': "You've reached your daily Claude limit",
  'alerta.aviso.titulo': "You're approaching your daily Claude limit",
  'alerta.diario.cuerpo': "Today you've used {hoy}% of your weekly quota (limit: {limite}%).",
  'alerta.sesionAviso.titulo': "You're running low on your 5-hour session",
  'alerta.sesionAviso.cuerpo': "You've used {porcentaje}% of the session.",
  'alerta.sesionReinicia': ' It resets at {hora}.',
  'alerta.sesionLimite.titulo': "You've reached your 5-hour session limit",
  'alerta.sesionLimite.conHora': "You'll be able to use Claude again at {hora}.",
  'alerta.sesionLimite.sinHora': "You'll have to wait for the session to reset.",
  'alerta.sesionReiniciada.titulo': 'Your 5-hour session has reset',
  'alerta.sesionReiniciada.cuerpo': 'You can use Claude again.',
  'alerta.exportado.titulo': 'History exported',
  'alerta.exportado.uno': '1 day saved to: {ruta}',
  'alerta.exportado.varios': '{n} days saved to: {ruta}',
  'alerta.formato.titulo': "The widget can't read your Claude usage",
  'alerta.formato.cuerpo': 'It looks like claude.ai changed its page. Open Claude Code in the project folder and ask it to check src/uso.js.',

  // ----- Several accounts -----
  'cuentas.principal': 'Main',
  'login.tituloCuenta': 'Sign in to Claude — {nombre}',
  'panel.cuentas': 'Accounts',
  'boton.cuenta': 'Account: {nombre} (click to see your accounts)',
  'cuentas.usar': 'Show this account',
  'cuentas.nombre': 'Account name',
  'cuentas.estado.conectado': 'Signed in',
  'cuentas.estado.sinSesion': 'Not signed in',
  'cuentas.estado.expirada': 'Session expired',
  'cuentas.cerrarSesion': 'Sign out',
  'cuentas.iniciarSesion': 'Sign in',
  'cuentas.eliminar': 'Delete this account',
  'cuentas.eliminarSeguro': 'Sure?',
  'cuentas.nueva': 'Name of the new account',
  'cuentas.agregar': 'Add',
  'cuentas.ayuda': 'Signing out keeps the history and the limits: use it to sign in with a different Claude account in the same slot. Deleting removes everything.',
  'cuentas.err.nombre': 'Type a name for the account.',
  'cuentas.err.maximo': 'You can have up to {n} accounts.',
  'aj.seccion.limiteDe': 'Daily limit · {nombre}',
  'resumen.sinSesion': 'Not signed in',
  'tray.cuenta': 'Account',
  'tray.cuentasAdministrar': 'Manage accounts…',
  'tray.cerrarSesionDe': 'Sign out of {nombre}',
  'aj.vista.cuentas': 'Accounts (all at once)',
  'aj.todas': 'Show all accounts at once',
  'aj.todas.ayuda': 'In the normal and compact views, with more than one account.',
  'tray.vista.cuentas': 'Accounts (all at once)',
  'boton.vistaNormal': 'Back to the normal view',
  'plan.free': 'Free',
  'plan.titulo': '{plan} plan',
  'extra.etiqueta': 'Extra use',
  'aj.seccion.semana': 'Weekly quota',
  'aj.semana.aviso': 'Warn me when it reaches',
  'aj.semana.activar': 'Turn on the weekly warning',
  'err.umbralSemana': 'The weekly quota warning must be between 50% and 99%.',
  'alerta.semanaAviso.titulo': "You're high on your weekly quota",
  'alerta.semanaAviso.cuerpo': "You've used {porcentaje}% of this week's quota.",
  'alerta.semanaAviso.reinicia': ' It resets {cuando}.',

  // ----- Mejoras: bandeja, avisos, reinicio, colores, historial -----
  'tray.versionNueva': 'Download Cupo {version}…',
  'tray.silencio': 'Mute alerts',
  'tray.silencio.hasta': 'Alerts muted until {hora}',
  'tray.silencio.unaHora': 'For 1 hour',
  'tray.silencio.manana': 'Until tomorrow',
  'tray.silencio.reactivar': 'Turn alerts back on',
  'alerta.version.titulo': 'A new version of Cupo is available',
  'alerta.version.cuerpo': 'Version {version} is out. Click to download it.',
  'alerta.sesionRitmo.titulo': "At this pace you'll run out of session",
  'alerta.sesionRitmo.cuerpo': "You'd hit the limit around {hora}, before the reset at {reinicio}.",
  'err.colores': 'The chosen colors are not valid.',
  'tiempo.ahora': 'now',
  'tiempo.min': 'in {m} min',
  'tiempo.horas': 'in {h} h',
  'tiempo.horasMin': 'in {h} h {m} min',
  'tiempo.dias': 'in {d} d',
  'tiempo.diasHoras': 'in {d} d {h} h',
  'historial.7': '7 days',
  'historial.30': '30 days',
  'historial.dias': 'Days shown',
  'historial.promedio': 'Average: {valor}% per day',
  'aj.reinicio': 'Show the reset as',
  'aj.reinicio.relativo': 'Countdown (in 2 h 15 min)',
  'aj.reinicio.hora': 'Time (15:06)',
  'aj.colores': 'Colors',
  'aj.colores.acento': 'Accent',
  'aj.colores.bajo': 'Low',
  'aj.colores.medio': 'Medium',
  'aj.colores.alto': 'High',
  'aj.colores.restablecer': 'Reset',
  'aj.iconoDeColor': "Tray icon colored by today's usage",
  'aj.sesion.ritmo': "Warn me if at this pace I'll run out of session",
  'aj.atajo': 'Ctrl + Alt + C shows or hides the widget',
  'aj.actualizaciones': 'Tell me when a new version is out',
};
