// en.js: all the app's texts in English.
//
// Every text has a key (e.g. 'tray.salir'), the same ones used in es.js. Pieces in braces, such as {hoy}, are
// replaced with values when the text is shown, so they must be kept exactly as they are.

module.exports = {
  // ----- Language data -----
  'meta.nombre': 'English',
  'meta.locale': 'en-US',          // used to write numbers (12.5) and day names
  'meta.csvSeparador': ',',        // English-language Excel separates columns with commas

  // ----- General -----
  'app.nombre': 'Headroom',
  'hoy.etiqueta': 'Today',
  'sesion.etiqueta': 'Session 5 h',
  'semana.etiqueta': 'Week',
  'reinicio.prefijo': 'Resets: ',
  'hoy.de': '{hoy}% of {limite}%',
  'lectura.cargando': 'Reading usage…',
  'sesion.sinActividad': 'no activity',

  // ----- Errors while reading usage -----
  'error.sinConexion': "Can't reach claude.ai",
  'error.formato': 'claude.ai data changed',
  'error.generico': "Couldn't read usage",

  // ----- Sign in -----
  'login.sinSesion': "You're not signed in",
  'login.expirada': 'Your session expired',
  'login.iniciar': 'Sign in',
  'login.reentrar': 'Sign in again',
  'login.titulo': 'Sign in to Claude',

  // ----- Panels -----
  'panel.historial': 'History',
  'panel.desglose': 'Weekly breakdown',
  "panel.productos": "Usage by product",
  "productos.ver": "Over time ›",
  "productos.semana": "This week",
  "productos.semanas": "Weeks",
  "productos.estaSemana": "now",
  "productos.semanasVacio": "No weeks saved yet. Each time your plan resets, one is added.",
  "productos.nota": "In % of your weekly quota: how much each product used.",
  "productos.vacio": "No days with the per-product detail yet. It fills up day by day.",
  'panel.proyeccion': 'Projection',
  'panel.ajustes': 'Settings',
  'panel.detalle': 'Details',
  'panel.cerrar': 'Close',
  "parte.separar": "Move to its own window",
  "parte.juntar": "Back to the widget",
  "parte.todas": "All accounts",
  'panel.cerrarAria': 'Close the panel',

  // ----- Card buttons -----
  'boton.historial': 'Usage history',
  'boton.historialAria': 'View the usage history',
  'boton.desglose': 'Weekly breakdown by product',
  'boton.desgloseAria': 'View the weekly breakdown by product',
  'boton.proyeccion': 'Projection: at this pace...',
  'boton.proyeccionAria': 'View the usage projection',
  'boton.ajustes': 'Settings',
  'boton.ajustesAria': 'Open settings',
  'boton.compacto': 'Compact view (one line)',
  'boton.compactoAria': 'Switch between the compact and the normal view',
  'boton.completo': 'Full view (everything at once)',
  'boton.completoAria': 'Switch between the full and the normal view',
  'boton.orientacion': 'Change the layout (vertical / horizontal)',
  'boton.orientacionAria': 'Switch between the vertical and the horizontal layout',

  // ----- History -----
  'historial.hoy': 'today',
  'historial.limiteDia': "That day's limit: {limite}%",

  // ----- Product names (the breakdown) -----
  'producto.claude_code': 'Claude Code',
  'producto.chat': 'Chats',
  'producto.cowork': 'Cowork',
  'producto.other': 'Other',

  // ----- Breakdown -----
  'desglose.sinDatos': 'No data yet. Wait for the first reading.',
  'desglose.sinDesglose': "claude.ai didn't provide the breakdown in this reading.",
  'desglose.nota': 'Split of what you used this week ({semana}% of your quota).',
  "desglose.notaVarias": "How each account’s usage this week is split (on the right, its % of the quota).",

  // ----- Projection -----
  'proy.dia.yaLlegaste': "You've already hit today's limit",
  'proy.dia.yaLlegaste.detalle': 'Better take it easy for the rest of the day.',
  'proy.dia.llegaras': "You'd hit your limit around {hora}",
  'proy.dia.llegaras.detalle': 'At this pace, before midnight.',
  'proy.dia.noLlegaras': "You wouldn't hit your limit today",
  'proy.dia.noLlegaras.detalle': "You'd end the day at ~{fin}%.",
  'proy.dia.sinUso': "You haven't used anything yet today",
  'proy.dia.sinUso.detalle': "At this pace you wouldn't reach the limit.",
  'proy.dia.sinDatos': "It's too early to estimate",
  'proy.dia.sinDatos.detalle': 'We need at least half an hour of measuring.',
  'proy.semana.yaLlegaste': "You've used up your weekly quota",
  'proy.semana.yaLlegaste.detalle': 'It resets {reinicio}.',
  'proy.semana.llegaras': "You'd reach 100% on {cuando}",
  'proy.semana.llegaras.detalle': 'Before the reset ({reinicio}).',
  'proy.semana.noLlegaras': "You wouldn't use up your quota this week",
  'proy.semana.noLlegaras.detalle': "You'd reach ~{fin}% before the reset.",
  'proy.semana.sinUso': "You haven't used anything yet this week",
  'proy.semana.sinUso.detalle': 'Nothing to project yet.',
  'proy.semana.sinDatos': "It's too early to estimate",
  'proy.semana.sinDatos.detalle': 'The week has just started.',
  'proy.sinDatos': 'No data yet',
  'proy.sinDatos.detalle': 'Wait for the first reading.',
  'proy.nota': 'Estimates based on your usage pace so far.',

  // ----- Settings -----
  'aj.seccion.vista': 'View',
  'aj.vista': 'View',
  'aj.vista.normal': 'Normal',
  'aj.vista.compacto': 'Compact (single line)',
  'aj.vista.completo': 'Full (everything at once)',
  'aj.disposicion': 'Layout',
  'aj.disposicion.vertical': 'Vertical (stacked bars)',
  'aj.disposicion.horizontal': 'Horizontal (side by side)',
  'aj.disposicion.ayuda': 'Applies to the normal view; the full view is always wide.',
  'aj.seccion.escala': 'Interface scale',
  'aj.escala.rapidos': 'Quick sizes',
  'aj.escala.ayuda': 'Makes everything bigger or smaller instantly. Also: Ctrl + mouse wheel (Ctrl 0 returns to 100%).',
  'aj.seccion.apariencia': 'Appearance',
  'aj.tema': 'Theme',
  'aj.tema.oscuro': 'Dark',
  'aj.tema.claro': 'Light',
  'aj.tema.auto': 'Automatic (like Windows)',
  'aj.transparencia': 'Background transparency',
  'aj.siempreEncima': 'Always on top of other windows',
  'aj.idioma': 'Language',
  'aj.idioma.auto': 'Automatic (like Windows)',
  'aj.seccion.limite': 'Daily limit',
  'aj.limite': 'Limit',
  'aj.aviso': 'Early warning',
  'aj.limite.ayuda': 'How much of your weekly quota you want to use at most per day. The warning must be lower than the limit.',
  'aj.limitesPorDia': 'A different limit for each day',
  "aj.limiteAuto": "Automatic limit",
  "aj.limiteAuto.ayuda": "Spreads what’s left of your week over the days until the reset. If you use little one day, you get more on the others.",
  "aj.limiteAuto.hoy": "Today you get {limite}%: what’s left of the week spread over the remaining days. The warning keeps the same proportion.",
  'aj.limitesPorDia.ayuda': 'The early warning adjusts itself, in the same proportion.',
  'aj.dia.0': 'Mo',
  'aj.dia.1': 'Tu',
  'aj.dia.2': 'We',
  'aj.dia.3': 'Th',
  'aj.dia.4': 'Fr',
  'aj.dia.5': 'Sa',
  'aj.dia.6': 'Su',
  'aj.dia.aria': 'Limit for {dia}',
  'aj.seccion.sesion': '5-hour session',
  'aj.sesion.aviso': 'Warn me when it reaches',
  'aj.sesion.activar': 'Turn on session alerts',
  'aj.seccion.consulta': 'Refresh',
  'aj.intervalo': 'Check usage every',
  'aj.intervalo.minutos': '{n} minutes',
  'aj.intervalo.hora': '1 hour',
  'aj.intervalo.ayuda': 'The minimum is 5 minutes.',
  "aj.pausarOculto": "Don’t check while the widget is hidden",
  "aj.pausarOculto.ayuda": "While it’s hidden there are no usage alerts. When you show it, it updates right away.",
  'aj.seccion.sistema': 'System and data',
  'aj.arranque': 'Open the widget when Windows starts',
  'aj.exportar': 'Export history (CSV)…',
  'aj.guardar': 'Save',
  'aj.guardado': 'Saved ✓',
  'aj.exportado': 'Done: {n} day(s) saved.',

  // ----- Settings validation errors -----
  'err.limite': 'The daily limit must be between 1% and 100%.',
  'err.avisoMinimo': 'The early warning must be at least 1%.',
  'err.avisoMenor': 'The early warning must be lower than the daily limit.',
  'err.intervalo': 'The refresh interval is not valid.',
  'err.umbralSesion': 'The 5-hour session warning must be between 50% and 99%.',
  'err.opcion': 'An option has an invalid value.',
  'err.vista': 'The selected view is not valid.',
  'err.disposicion': 'The selected layout is not valid.',
  'err.tema': 'The selected theme is not valid.',
  'err.idioma': 'The selected language is not valid.',
  'err.transparencia': 'The transparency must leave the widget between 40% and 100% visible.',
  'err.escala': 'The scale must be between {min}% and {max}%.',
  'err.limitesSiete': 'The per-day limits must be seven values, Monday to Sunday.',
  'err.limiteDia': "Each day's limit must be between 1% and 100%.",

  // ----- Tray menu (next to the clock) -----
  'tray.actualizado': 'Headroom · updated {hora}',
  'tray.actualizar': 'Refresh',
  'tray.mostrarOcultar': 'Show / Hide',
  'tray.siempreEncima': 'Always on top',
  'tray.historial': 'History',
  "boton.productos": "Usage by product over time",
  "tray.productos": "Usage by product",
  "historial.pocos": "It fills in with each check (every 5 minutes).",
  "panel.bienvenida": "How it works",
  "tray.bienvenida": "How it works",
  "bienvenida.hoy.titulo": "Today",
  "bienvenida.hoy": "What you’ve used today against your daily limit. You choose the limit in Settings, or let it be calculated for you.",
  "bienvenida.plan.titulo": "5-hour session and Week",
  "bienvenida.plan": "Your Claude plan’s limits, and how long until they reset.",
  "bienvenida.clic.titulo": "Click the name of a bar",
  "bienvenida.clic": "Opens the official details on claude.ai.",
  "bienvenida.cuentas.titulo": "Several accounts",
  "bienvenida.cuentas": "Click the label with the account name, top left.",
  "bienvenida.mover.titulo": "Move and hide it",
  "bienvenida.mover": "Drag it wherever you like. Ctrl + Alt + C hides or shows it.",
  "bienvenida.listo": "Got it",
  "tray.verEnClaude": "See usage on claude.ai",
  "boton.verEnClaude": "See the details on claude.ai",
  'tray.desglose': 'Weekly breakdown',
  'tray.proyeccion': 'Projection',
  'tray.vista': 'View',
  'tray.vista.normal': 'Normal',
  'tray.vista.compacto': 'Compact (one line)',
  'tray.vista.completo': 'Full (everything at once)',
  'tray.disposicion.vertical': 'Vertical layout',
  'tray.disposicion.horizontal': 'Horizontal layout',
  'tray.exportar': 'Export history (CSV)…',
  'tray.ajustes': 'Settings',
  'tray.cerrarSesion': 'Sign out',
  'tray.salir': 'Quit',

  // ----- Exporting the history -----
  'exportar.titulo': 'Export usage history',
  'exportar.filtro': 'CSV file (opens in Excel)',
  'exportar.nombreArchivo': 'claude-usage-history-{fecha}.csv',
  'exportar.vacio': 'There are no recorded days to export yet.',
  'exportar.error': 'Could not save the file: {mensaje}',
  'csv.fecha': 'Date',
  'csv.uso': 'Daily usage (%)',
  'csv.limite': 'Daily limit (%)',
  'csv.supero': 'Exceeded the limit?',
  'csv.si': 'Yes',
  'csv.no': 'No',

  // ----- Windows notifications -----
  'alerta.limite.titulo': "You've reached your daily Claude limit",
  'alerta.aviso.titulo': "You're approaching your daily Claude limit",
  'alerta.diario.cuerpo': "Today you've used {hoy}% of your weekly quota (limit: {limite}%).",
  'alerta.sesionAviso.titulo': "You're running low on your 5-hour session",
  'alerta.sesionAviso.cuerpo': "You've used {porcentaje}% of the session.",
  'alerta.sesionReinicia': ' It resets at {hora}.',
  'alerta.sesionLimite.titulo': "You've reached your 5-hour session limit",
  'alerta.sesionLimite.conHora': "You'll be able to use Claude again at {hora}.",
  'alerta.sesionLimite.sinHora': "You'll have to wait for the session to reset.",
  'alerta.sesionReiniciada.titulo': 'Your 5-hour session has reset',
  'alerta.sesionReiniciada.cuerpo': 'You can use Claude again.',
  'alerta.exportado.titulo': 'History exported',
  'alerta.exportado.uno': '1 day saved to: {ruta}',
  'alerta.exportado.varios': '{n} days saved to: {ruta}',
  'alerta.formato.titulo': "The widget can't read your Claude usage",
  'alerta.formato.cuerpo': 'It looks like claude.ai changed its page. Open Claude Code in the project folder and ask it to check src/uso.js.',

  // ----- Several accounts -----
  'cuentas.principal': 'Main',
  'login.tituloCuenta': 'Sign in to Claude — {nombre}',
  'panel.cuentas': 'Accounts',
  'boton.cuenta': "Account: {nombre} (click to see, switch or add accounts)",
  'cuentas.usar': 'Show this account',
  'cuentas.nombre': 'Account name',
  'cuentas.estado.conectado': 'Signed in',
  'cuentas.estado.sinSesion': 'Not signed in',
  'cuentas.estado.expirada': 'Session expired',
  'cuentas.cerrarSesion': 'Sign out',
  'cuentas.iniciarSesion': 'Sign in',
  'cuentas.eliminar': 'Delete this account',
  'cuentas.eliminarSeguro': 'Sure?',
  'cuentas.nueva': "Name (e.g. Work)",
  'cuentas.agregar': 'Add',
  "tray.cuentaAgregar": "Add account…",
  "cuentas.pasos": "1. Type a name to recognize it (for example, Work).\n2. Click Add.\n3. claude.ai opens: sign in with that account.",
  "cuentas.nuevaTitulo": "Add another Claude account",
  'cuentas.ayuda': 'Signing out keeps the history and the limits: use it to sign in with a different Claude account in the same slot. Deleting removes everything.',
  'cuentas.err.nombre': 'Type a name for the account.',
  'cuentas.err.maximo': 'You can have up to {n} accounts.',
  'aj.seccion.limiteDe': 'Daily limit · {nombre}',
  'resumen.sinSesion': 'Not signed in',
  'tray.cuenta': 'Account',
  'tray.cuentasAdministrar': 'Manage accounts…',
  'tray.cerrarSesionDe': 'Sign out of {nombre}',
  'aj.vista.cuentas': 'Accounts (all at once)',
  "aj.vista.mini": "Minimal (a circle)",
  "tray.vista.mini": "Minimal (a circle)",
  "mini.volver": "Click to go back to the normal view",
  'aj.todas': 'Show all accounts at once',
  'aj.todas.ayuda': 'In the normal and compact views, with more than one account.',
  "aj.separadas": "Each account in its own window",
  "aj.separadas.ayuda": "Each one moves separately and has its own view.",
  'tray.vista.cuentas': 'Accounts (all at once)',
  'boton.vistaNormal': 'Back to the normal view',
  'plan.free': 'Free',
  'plan.titulo': '{plan} plan',
  'extra.etiqueta': 'Extra use',
  'aj.seccion.semana': 'Weekly quota',
  'aj.semana.aviso': 'Warn me when it reaches',
  'aj.semana.activar': 'Turn on the weekly warning',
  'err.umbralSemana': 'The weekly quota warning must be between 50% and 99%.',
  "alerta.contexto.titulo": "Good time to compact",
  "alerta.contexto.cuerpo": "The chat “{chat}” is at {porcentaje}% of its context. Type /compact in Claude Code to summarize it.",
  "aj.seccion.contexto": "Claude Code context window",
  "chats.sinNombre": "Untitled chat",
  "chats.titulo": "Claude Code context window",
  "aj.contexto.mostrar": "Show the context of each chat",
  "aj.contexto.aviso": "Warn me at",
  "aj.contexto.activar": "Remind me to compact (and every 10% more)",
  "aj.contexto.tamano": "Context size",
  "aj.contexto.auto": "Automatic",
  "aj.contexto.ayuda": "Only works if you use Claude Code on this same computer, and only with one account in Headroom. It can’t see claude.ai chats (on the web or in the app) or chats from other computers. Shows the chats from the last 3 hours (up to 5).",
  "err.umbralContexto": "The context reminder must be between 10% and 95%.",
  'alerta.semanaAviso.titulo': "You're high on your weekly quota",
  'alerta.semanaAviso.cuerpo': "You've used {porcentaje}% of this week's quota.",
  'alerta.semanaAviso.reinicia': ' It resets {cuando}.',

  // ----- Mejoras: bandeja, avisos, reinicio, colores, historial -----
  'tray.versionNueva': "Update to Headroom {version}",
  "tray.actualizando": "Downloading the update… {progreso}%",
  'tray.silencio': 'Mute alerts',
  'tray.silencio.hasta': 'Alerts muted until {hora}',
  'tray.silencio.unaHora': 'For 1 hour',
  'tray.silencio.manana': 'Until tomorrow',
  'tray.silencio.reactivar': 'Turn alerts back on',
  'alerta.version.titulo': 'A new version of Headroom is available',
  'alerta.version.cuerpo': "Version {version} is available. Click to update.",
  'alerta.sesionRitmo.titulo': "At this pace you'll run out of session",
  'alerta.sesionRitmo.cuerpo': "You'd hit the limit around {hora}, before the reset at {reinicio}.",
  'err.colores': 'The chosen colors are not valid.',
  'tiempo.ahora': 'now',
  'tiempo.min': 'in {m} min',
  'tiempo.horas': 'in {h} h',
  'tiempo.horasMin': 'in {h} h {m} min',
  'tiempo.dias': 'in {d} d',
  'tiempo.diasHoras': 'in {d} d {h} h',
  'historial.7': '7 days',
  "historial.dia": "Today",
  "historial.diaVacio": "No readings yet today. The chart fills up with each check.",
  "historial.porDia": "Usage per day",
  "historial.diasVacio": "No days saved yet. The chart fills up day by day.",
  "historial.limite": "your limit",
  'historial.30': '30 days',
  'historial.dias': 'Days shown',
  'historial.promedio': 'Average: {valor}% per day',
  'aj.reinicio': 'Show the reset as',
  'aj.reinicio.relativo': 'Countdown (in 2 h 15 min)',
  'aj.reinicio.hora': 'Time (15:06)',
  'aj.colores': 'Colors',
  'aj.colores.acento': 'Accent',
  'aj.colores.bajo': 'Low',
  'aj.colores.medio': 'Medium',
  'aj.colores.alto': 'High',
  'aj.colores.restablecer': 'Reset',
  'aj.iconoDeColor': "Tray icon colored by today's usage",
  'aj.sesion.ritmo': "Warn me if at this pace I'll run out of session",
  'aj.atajo': 'Ctrl + Alt + C shows or hides the widget',
  'aj.actualizaciones': 'Tell me when a new version is out',
  "aj.resumenes": "Summary of yesterday and of the week",
  "alerta.resumenDia.titulo": "Your day yesterday",
  "alerta.resumenDia.cuerpo": "Yesterday you used {uso}% of your weekly quota (your limit was {limite}%).",
  "alerta.resumenDia.pasado": "Yesterday you used {uso}% of your weekly quota: over your {limite}% limit.",
  "alerta.resumenSemana.titulo": "Your week is over",
  "alerta.resumenSemana.cuerpo": "You used {semana}% of your weekly quota.",
  "alerta.resumenSemana.dia": "Your highest day was {dia} ({uso}%).",
  "historial.horas": "Hours",
  "historial.horas.titulo": "What time of day you use it most",
  "horas.pico": "Peak {desde}–{hasta} h",
  "horas.vacio": "No hourly data yet: it fills in with each day of use.",
  "horas.dias": "Average of {n} day(s)",
  "comp.arriba": "You are {n}% above last week at this same point (you were at {antes}%).",
  "comp.abajo": "You are {n}% below last week at this same point (you were at {antes}%).",
  "comp.igual": "You are about level with last week at this same point (you were at {antes}%).",
  "comp.aprox": "This is an estimate: it will be exact from next week on.",
  "comp.corto.arriba": "▲ {n}% more than last week",
  "comp.corto.abajo": "▼ {n}% less than last week",
  "comp.corto.igual": "= Same as last week",
  "aj.copia.guardar": "Save backup…",
  "aj.copia.restaurar": "Restore backup…",
  "aj.copia.ayuda": "The backup keeps your settings, accounts and history. It does not keep your sign-ins: on another computer you will have to sign in to each account again.",
  "copia.guardar.titulo": "Save backup",
  "copia.restaurar.titulo": "Restore backup",
  "copia.filtro": "Headroom backup",
  "copia.guardada": "Done: backup saved.",
  "copia.invalida": "That file is not a Headroom backup.",
  "copia.confirmar": "Restore the backup from {fecha} ({n} account(s))?",
  "copia.confirmar.detalle": "Your current settings, accounts and history will be replaced. Headroom will close and open again.",
  "copia.confirmar.si": "Restore",
  "copia.confirmar.no": "Cancel",
  "aj.seccion.copia": "Backup",
  "productos.notaModelos": "Dashed ({nombres}): % of its own weekly limit.",
  "aj.seguirAClaude": "Show only while Claude is open",
  "aj.seguirAClaude.ayuda": "It appears when you open the Claude app (or Claude Code) on this computer and hides when you close it. Headroom stays in the tray; it helps to also turn on \"Open the widget when Windows starts\". Claude in the browser is not detected.",
  "acerca.titulo": "About",
  "acerca.version": "Headroom {version} (installed)",
  "acerca.buscar": "Check for updates",
  "acerca.buscando": "Checking…",
  "acerca.alDia": "You have the latest version.",
  "acerca.hayNueva": "A new version is available: {version}.",
  "acerca.actualizar": "Update to {version}",
  "acerca.descargando": "Downloading… Headroom will close and open again.",
  "acerca.sinRespuesta": "Could not check. Check your connection and try again later.",
  "acerca.credito": "Made by {autor} and Claude.",
  "comp.hoy.arriba": "You are {n}% above yesterday at this same time (you were at {antes}%).",
  "comp.hoy.abajo": "You are {n}% below yesterday at this same time (you were at {antes}%).",
  "comp.hoy.igual": "You are about level with yesterday at this same time (you were at {antes}%).",
  "comp.hoy.corto.arriba": "▲ {n}% more than yesterday at this time",
  "comp.hoy.corto.abajo": "▼ {n}% less than yesterday at this time",
  "comp.hoy.corto.igual": "= Same as yesterday at this time",
  "comp.sesion.arriba": "You are {n}% above your previous session at this same point (you were at {antes}%).",
  "comp.sesion.abajo": "You are {n}% below your previous session at this same point (you were at {antes}%).",
  "comp.sesion.igual": "You are about level with your previous session at this same point (you were at {antes}%).",
  "comp.sesion.corto.arriba": "▲ {n}% more than the previous session",
  "comp.sesion.corto.abajo": "▼ {n}% less than the previous session",
  "comp.sesion.corto.igual": "= Same as the previous session",
  "aj.vista.tablero": "Dashboard (all the charts)",
  "tablero.titulo": "Dashboard",
  "tablero.hoy": "Today, hour by hour",
  "tablero.dias": "Last 30 days",
  "tablero.horas": "Busiest hours",
  "tablero.prodHoy": "By product: today",
  "tablero.prodSemana": "By product: this week",
  "tablero.semanas": "By product: week by week",
  "tray.vista.tablero": "Dashboard (all the charts)",
  "boton.tablero": "Dashboard (all the charts)",
  "boton.mini": "Minimal view (a circle)",
  "aj.sinBarras": "Numbers only (hide the bars)",
  "ayuda.hoy": "TODAY: what you have used today ({hoy}% of your weekly quota) against the daily limit you chose ({limite}%). The bar fills up when you reach that limit. It helps you spread the week instead of spending it in a few days. Change the limit in Settings.",
  "ayuda.sesion": "5-HOUR SESSION: your plan’s limit that resets every 5 hours. If it reaches 100%, you have to wait for the reset shown.",
  "ayuda.semana": "WEEK: how much of your plan’s weekly quota you have used. If it reaches 100%, you have to wait for the weekly reset.",
  "ayuda.modelo": "{nombre}: that model’s own weekly limit on your plan. It is separate from the general weekly quota.",
  "ayuda.credito": "EXTRA USAGE: what you have spent of your extra credit this month (usage billed separately once you pass your plan’s limits).",
  "aj.consultaRapida": "Every 2 minutes when the session passes 70%",
  "aj.consultaRapida.ayuda": "While the 5-hour session is between 70% and 100%, usage is checked every 2 minutes so alerts arrive in time. The rest of the time the interval above applies. It means more requests to claude.ai: turn it on only if you need it.",
  "aj.semana.ritmo": "Alert me if at this pace I will use up the week",
  "alerta.semanaRitmo.titulo": "At this pace you will use up the week",
  "alerta.semanaRitmo.cuerpo": "You would reach 100% {cuando}, before the reset ({reinicio}).",
  "panel.estadisticas": "Statistics",
  "boton.estadisticas": "Statistics: records, streaks and habits",
  "est.masAlto": "Highest day",
  "est.promedio": "Average per day",
  "est.racha": "Streak under your limit",
  "est.sobre": "Days over the limit",
  "est.sobra": "Left over per week",
  "est.sugerido": "Suggested limit",
  "est.sesiones": "Sessions used up",
  "est.horaAgota": "Usually used up",
  "est.dias": "{n} day(s)",
  "est.de30": "in 30 days",
  "est.en7": "in 7 days",
  "est.semanas": "average of {n} week(s)",
  "est.sugerido.detalle": "you use Claude about {n} days a week",
  "est.sesiones.detalle": "{a} of {n} in 7 days",
  "est.hora": "around {hora}",
  "est.horaAgota.detalle": "the most frequent hour",
  "est.faltan": "Not enough data yet",
  "est.porDia": "By day of the week",
  "est.mapa": "When you use it most (day and hour)",
  "est.informe": "Save report…",
  "est.informe.listo": "Report saved.",
  "est.nota": "Based on the last 30 days (weeks and sessions: everything stored).",
  "informe.titulo": "Claude usage report",
  "informe.generado": "Generated on {fecha} with Headroom",
  "informe.porMes": "Month by month",
  "informe.mes": "Month",
  "informe.diasConUso": "Days with usage",
  "informe.total": "Sum of daily usage",
  "informe.ultimos": "Last 30 days",
  "informe.dia": "Day",
  "informe.uso": "Usage",
  "informe.limite": "Limit",
  "informe.archivo": "headroom-report-{fecha}.html",
  "informe.filtro": "Web page",
};
