// es.js: todos los textos de la app en español (de Chile).
//
// Cada texto tiene una clave (ej. 'tray.salir'). Los trozos entre llaves, como {hoy}, se reemplazan por valores
// al mostrar el texto. Para agregar un idioma nuevo: copiar este archivo (por ejemplo a "pt.js"), traducir los
// textos SIN cambiar las claves ni las {llaves}, y anotar el idioma en idiomas.js.

module.exports = {
  // ----- Datos del idioma -----
  'meta.nombre': 'Español',
  'meta.locale': 'es-CL',          // para escribir números (12,5) y nombres de días
  'meta.csvSeparador': ';',        // el Excel en español separa las columnas con punto y coma

  // ----- General -----
  'app.nombre': 'Headroom',
  'hoy.etiqueta': 'Hoy',
  'sesion.etiqueta': 'Sesión 5 h',
  'semana.etiqueta': 'Semana',
  'reinicio.prefijo': 'Reinicio: ',
  'hoy.de': '{hoy}% de {limite}%',
  'lectura.cargando': 'Leyendo uso…',
  'sesion.sinActividad': 'sin actividad',

  // ----- Errores al leer el uso -----
  'error.sinConexion': 'Sin conexión a claude.ai',
  'error.formato': 'Datos de claude.ai cambiaron',
  'error.generico': 'No se pudo leer el uso',

  // ----- Inicio de sesión -----
  'login.sinSesion': 'No has iniciado sesión',
  'login.expirada': 'Tu sesión expiró',
  'login.iniciar': 'Iniciar sesión',
  'login.reentrar': 'Volver a entrar',
  'login.titulo': 'Iniciar sesión en Claude',

  // ----- Paneles -----
  'panel.historial': 'Historial',
  'panel.desglose': 'Desglose de la semana',
  "panel.productos": "Uso por producto",
  "productos.ver": "A lo largo del tiempo ›",
  "productos.semana": "Esta semana",
  "productos.semanas": "Semanas",
  "productos.estaSemana": "esta",
  "productos.semanasVacio": "Todavía no hay semanas guardadas. Cada vez que se reinicia tu plan, se suma una.",
  "productos.nota": "En % de tu cuota semanal: cuánto usó cada producto.",
  "productos.vacio": "Todavía no hay días con el detalle por producto. Se va llenando día a día.",
  'panel.proyeccion': 'Proyección',
  'panel.ajustes': 'Ajustes',
  'panel.detalle': 'Detalle',
  'panel.cerrar': 'Cerrar',
  "parte.separar": "Sacar a su propia ventana",
  "parte.juntar": "Volver al widget",
  "parte.todas": "Todas las cuentas",
  'panel.cerrarAria': 'Cerrar el panel',

  // ----- Botones de la tarjeta -----
  'boton.historial': 'Historial de uso',
  'boton.historialAria': 'Ver el historial de uso',
  'boton.desglose': 'Desglose de la semana por producto',
  'boton.desgloseAria': 'Ver el desglose de la semana por producto',
  'boton.proyeccion': 'Proyección: a este ritmo...',
  'boton.proyeccionAria': 'Ver la proyección de uso',
  'boton.ajustes': 'Ajustes',
  'boton.ajustesAria': 'Abrir los ajustes',
  'boton.compacto': 'Vista compacta (una línea)',
  'boton.compactoAria': 'Cambiar entre la vista compacta y la normal',
  'boton.completo': 'Vista completa (todo a la vez)',
  'boton.completoAria': 'Cambiar entre la vista completa y la normal',
  'boton.orientacion': 'Cambiar la disposición (vertical / horizontal)',
  'boton.orientacionAria': 'Cambiar entre la disposición vertical y la horizontal',

  // ----- Historial -----
  'historial.hoy': 'hoy',
  'historial.limiteDia': 'Límite de ese día: {limite}%',

  // ----- Nombres de los productos (el desglose) -----
  'producto.claude_code': 'Claude Code',
  'producto.chat': 'Chats',
  'producto.cowork': 'Cowork',
  'producto.other': 'Otros',

  // ----- Desglose -----
  'desglose.sinDatos': 'Todavía no hay datos. Espera a la primera lectura.',
  'desglose.sinDesglose': 'claude.ai no entregó el desglose en esta lectura.',
  'desglose.nota': 'Reparto de lo que usaste esta semana ({semana}% de tu cuota).',
  "desglose.notaVarias": "Reparto de lo que usó cada cuenta esta semana (a la derecha, su % de la cuota).",

  // ----- Proyección -----
  'proy.dia.yaLlegaste': 'Ya llegaste a tu límite de hoy',
  'proy.dia.yaLlegaste.detalle': 'Mejor ir con calma el resto del día.',
  'proy.dia.llegaras': 'Llegarías a tu límite hacia las {hora}',
  'proy.dia.llegaras.detalle': 'A este ritmo, antes de medianoche.',
  'proy.dia.noLlegaras': 'No llegarías a tu límite hoy',
  'proy.dia.noLlegaras.detalle': 'Terminarías el día en ~{fin}%.',
  'proy.dia.sinUso': 'Todavía no has usado nada hoy',
  'proy.dia.sinUso.detalle': 'Con este ritmo no llegarías al límite.',
  'proy.dia.sinDatos': 'Aún es pronto para estimar',
  'proy.dia.sinDatos.detalle': 'Falta al menos media hora de medición.',
  'proy.semana.yaLlegaste': 'Ya agotaste tu cuota semanal',
  'proy.semana.yaLlegaste.detalle': 'Se reinicia {reinicio}.',
  'proy.semana.llegaras': 'Llegarías al 100% el {cuando}',
  'proy.semana.llegaras.detalle': 'Antes del reinicio ({reinicio}).',
  'proy.semana.noLlegaras': 'No agotarías tu cuota esta semana',
  'proy.semana.noLlegaras.detalle': 'Llegarías a ~{fin}% antes del reinicio.',
  'proy.semana.sinUso': 'Todavía no has usado nada esta semana',
  'proy.semana.sinUso.detalle': 'No hay nada que proyectar aún.',
  'proy.semana.sinDatos': 'Aún es pronto para estimar',
  'proy.semana.sinDatos.detalle': 'La semana acaba de empezar.',
  'proy.sinDatos': 'Todavía no hay datos',
  'proy.sinDatos.detalle': 'Espera a la primera lectura.',
  'proy.nota': 'Estimaciones según tu ritmo de uso hasta ahora.',

  // ----- Ajustes -----
  'aj.seccion.vista': 'Vista',
  'aj.vista': 'Vista',
  'aj.vista.normal': 'Normal',
  'aj.vista.compacto': 'Compacto (una sola línea)',
  'aj.vista.completo': 'Completo (todo a la vez)',
  'aj.disposicion': 'Disposición',
  'aj.disposicion.vertical': 'Vertical (barras apiladas)',
  'aj.disposicion.horizontal': 'Horizontal (lado a lado)',
  'aj.disposicion.ayuda': 'Vale para la vista normal; la completa siempre es ancha.',
  'aj.seccion.escala': 'Escala de la interfaz',
  'aj.escala.rapidos': 'Tamaños rápidos',
  'aj.escala.ayuda': 'Agranda o achica todo al instante. También: Ctrl + rueda del mouse (Ctrl 0 vuelve al 100%).',
  'aj.seccion.apariencia': 'Apariencia',
  'aj.tema': 'Tema',
  'aj.tema.oscuro': 'Oscuro',
  'aj.tema.claro': 'Claro',
  'aj.tema.auto': 'Automático (como Windows)',
  'aj.transparencia': 'Transparencia del fondo',
  'aj.siempreEncima': 'Siempre encima de otras ventanas',
  'aj.idioma': 'Idioma',
  'aj.idioma.auto': 'Automático (como Windows)',
  'aj.seccion.limite': 'Límite diario',
  'aj.limite': 'Límite',
  'aj.aviso': 'Aviso previo',
  'aj.limite.ayuda': 'Cuánto de tu cuota semanal quieres usar como máximo al día. El aviso debe ser menor que el límite.',
  'aj.limitesPorDia': 'Un límite distinto para cada día',
  "aj.limiteAuto": "Límite automático",
  "aj.limiteAuto.ayuda": "Reparte lo que te queda de la semana entre los días que faltan para el reinicio. Si un día usas poco, los demás te toca más.",
  "aj.limiteAuto.hoy": "Hoy te toca {limite}%: lo que te queda de la semana repartido entre los días que faltan. El aviso previo guarda la misma proporción.",
  'aj.limitesPorDia.ayuda': 'El aviso previo se ajusta solo, en la misma proporción.',
  'aj.dia.0': 'Lu',
  'aj.dia.1': 'Ma',
  'aj.dia.2': 'Mi',
  'aj.dia.3': 'Ju',
  'aj.dia.4': 'Vi',
  'aj.dia.5': 'Sá',
  'aj.dia.6': 'Do',
  'aj.dia.aria': 'Límite del día {dia}',
  'aj.seccion.sesion': 'Sesión de 5 horas',
  'aj.sesion.aviso': 'Avisarme al llegar a',
  'aj.sesion.activar': 'Activar los avisos de la sesión',
  'aj.seccion.consulta': 'Consulta',
  'aj.intervalo': 'Consultar el uso cada',
  'aj.intervalo.minutos': '{n} minutos',
  'aj.intervalo.hora': '1 hora',
  'aj.intervalo.ayuda': 'El mínimo es 5 minutos.',
  "aj.pausarOculto": "No consultar mientras el widget está oculto",
  "aj.pausarOculto.ayuda": "Mientras está oculto no hay avisos de uso. Al mostrarlo, se actualiza al instante.",
  'aj.seccion.sistema': 'Sistema y datos',
  'aj.arranque': 'Abrir el widget al iniciar Windows',
  'aj.exportar': 'Exportar historial (CSV)…',
  'aj.guardar': 'Guardar',
  'aj.guardado': 'Guardado ✓',
  'aj.exportado': 'Listo: se guardaron {n} día(s).',

  // ----- Errores de validación de los ajustes -----
  'err.limite': 'El límite diario debe estar entre 1% y 100%.',
  'err.avisoMinimo': 'El aviso previo debe ser de al menos 1%.',
  'err.avisoMenor': 'El aviso previo debe ser menor que el límite diario.',
  'err.intervalo': 'El intervalo de consulta no es válido.',
  'err.umbralSesion': 'El aviso de la sesión de 5 horas debe estar entre 50% y 99%.',
  'err.opcion': 'Hay una opción con un valor no válido.',
  'err.vista': 'La vista elegida no es válida.',
  'err.disposicion': 'La disposición elegida no es válida.',
  'err.tema': 'El tema elegido no es válido.',
  'err.idioma': 'El idioma elegido no es válido.',
  'err.transparencia': 'La transparencia debe dejar el widget entre 40% y 100% visible.',
  'err.escala': 'El tamaño debe estar entre {min}% y {max}%.',
  'err.limitesSiete': 'Los límites por día deben ser siete valores, de lunes a domingo.',
  'err.limiteDia': 'El límite de cada día debe estar entre 1% y 100%.',

  // ----- Menú de la bandeja (junto al reloj) -----
  'tray.actualizado': 'Headroom · actualizado {hora}',
  'tray.actualizar': 'Actualizar',
  'tray.mostrarOcultar': 'Mostrar / Ocultar',
  'tray.siempreEncima': 'Siempre encima',
  'tray.historial': 'Historial',
  "boton.productos": "Uso por producto a lo largo del tiempo",
  "tray.productos": "Uso por producto",
  "historial.pocos": "Se va dibujando con cada consulta (cada 5 minutos).",
  "panel.bienvenida": "Cómo funciona",
  "tray.bienvenida": "Cómo funciona",
  "bienvenida.hoy.titulo": "Hoy",
  "bienvenida.hoy": "Lo que llevas usado hoy contra tu límite diario. El límite lo eliges tú en Ajustes, o deja que se calcule solo.",
  "bienvenida.plan.titulo": "Sesión 5 h y Semana",
  "bienvenida.plan": "Los límites de tu plan de Claude, y cuánto falta para que se reinicien.",
  "bienvenida.clic.titulo": "Clic en el nombre de una barra",
  "bienvenida.clic": "Abre el detalle oficial en claude.ai.",
  "bienvenida.cuentas.titulo": "Varias cuentas",
  "bienvenida.cuentas": "Clic en la etiqueta con el nombre de la cuenta, arriba a la izquierda.",
  "bienvenida.mover.titulo": "Moverlo y ocultarlo",
  "bienvenida.mover": "Arrástralo a donde quieras. Ctrl + Alt + C lo oculta o lo muestra.",
  "bienvenida.listo": "Entendido",
  "tray.verEnClaude": "Ver el uso en claude.ai",
  "boton.verEnClaude": "Ver el detalle en claude.ai",
  'tray.desglose': 'Desglose de la semana',
  'tray.proyeccion': 'Proyección',
  'tray.vista': 'Vista',
  'tray.vista.normal': 'Normal',
  'tray.vista.compacto': 'Compacto (una línea)',
  'tray.vista.completo': 'Completo (todo a la vez)',
  'tray.disposicion.vertical': 'Disposición vertical',
  'tray.disposicion.horizontal': 'Disposición horizontal',
  'tray.exportar': 'Exportar historial (CSV)…',
  'tray.ajustes': 'Ajustes',
  'tray.cerrarSesion': 'Cerrar sesión',
  'tray.salir': 'Salir',

  // ----- Exportar el historial -----
  'exportar.titulo': 'Exportar historial de uso',
  'exportar.filtro': 'Archivo CSV (se abre en Excel)',
  'exportar.nombreArchivo': 'historial-uso-claude-{fecha}.csv',
  'exportar.vacio': 'Todavía no hay días registrados para exportar.',
  'exportar.error': 'No se pudo guardar el archivo: {mensaje}',
  'csv.fecha': 'Fecha',
  'csv.uso': 'Uso del día (%)',
  'csv.limite': 'Límite del día (%)',
  'csv.supero': '¿Superó el límite?',
  'csv.si': 'Sí',
  'csv.no': 'No',

  // ----- Notificaciones de Windows -----
  'alerta.limite.titulo': 'Llegaste a tu límite diario de Claude',
  'alerta.aviso.titulo': 'Te acercas a tu límite diario de Claude',
  'alerta.diario.cuerpo': 'Hoy llevas {hoy}% de tu cuota semanal (límite: {limite}%).',
  'alerta.sesionAviso.titulo': 'Te queda poco de tu sesión de 5 horas',
  'alerta.sesionAviso.cuerpo': 'Llevas {porcentaje}% de la sesión.',
  'alerta.sesionReinicia': ' Se reinicia a las {hora}.',
  'alerta.sesionLimite.titulo': 'Llegaste al límite de tu sesión de 5 horas',
  'alerta.sesionLimite.conHora': 'Podrás volver a usar Claude a las {hora}.',
  'alerta.sesionLimite.sinHora': 'Tendrás que esperar a que se reinicie la sesión.',
  'alerta.sesionReiniciada.titulo': 'Tu sesión de 5 horas se reinició',
  'alerta.sesionReiniciada.cuerpo': 'Ya puedes volver a usar Claude.',
  'alerta.exportado.titulo': 'Historial exportado',
  'alerta.exportado.uno': 'Se guardó 1 día en: {ruta}',
  'alerta.exportado.varios': 'Se guardaron {n} días en: {ruta}',
  'alerta.formato.titulo': 'El widget no puede leer tu uso de Claude',
  'alerta.formato.cuerpo': 'Parece que claude.ai cambió su página. Abre Claude Code en la carpeta del proyecto y pídele que revise src/uso.js.',

  // ----- Varias cuentas -----
  'cuentas.principal': 'Principal',
  'login.tituloCuenta': 'Iniciar sesión en Claude — {nombre}',
  'panel.cuentas': 'Cuentas',
  'boton.cuenta': "Cuenta: {nombre} (clic para ver, cambiar o agregar cuentas)",
  'cuentas.usar': 'Mostrar esta cuenta',
  'cuentas.nombre': 'Nombre de la cuenta',
  'cuentas.estado.conectado': 'Sesión iniciada',
  'cuentas.estado.sinSesion': 'Sin sesión',
  'cuentas.estado.expirada': 'Sesión expirada',
  'cuentas.cerrarSesion': 'Cerrar sesión',
  'cuentas.iniciarSesion': 'Iniciar sesión',
  'cuentas.eliminar': 'Eliminar esta cuenta',
  'cuentas.eliminarSeguro': '¿Seguro?',
  'cuentas.nueva': "Nombre (ej.: Trabajo)",
  'cuentas.agregar': 'Agregar',
  "tray.cuentaAgregar": "Agregar cuenta…",
  "cuentas.pasos": "1. Escribe un nombre para reconocerla (por ejemplo, Trabajo).\n2. Pulsa Agregar.\n3. Se abre claude.ai: entra con esa cuenta.",
  "cuentas.nuevaTitulo": "Agregar otra cuenta de Claude",
  'cuentas.ayuda': 'Cerrar sesión conserva el historial y los límites: sirve para entrar con otra cuenta de Claude en el mismo lugar. Eliminar lo borra todo.',
  'cuentas.err.nombre': 'Escribe un nombre para la cuenta.',
  'cuentas.err.maximo': 'Puedes tener hasta {n} cuentas.',
  'aj.seccion.limiteDe': 'Límite diario · {nombre}',
  'resumen.sinSesion': 'Sin sesión',
  'tray.cuenta': 'Cuenta',
  'tray.cuentasAdministrar': 'Administrar cuentas…',
  'tray.cerrarSesionDe': 'Cerrar sesión de {nombre}',
  'aj.vista.cuentas': 'Cuentas (todas a la vez)',
  "aj.vista.mini": "Mínimo (un círculo)",
  "tray.vista.mini": "Mínimo (un círculo)",
  "mini.volver": "Clic para volver a la vista normal",
  'aj.todas': 'Mostrar todas las cuentas a la vez',
  'aj.todas.ayuda': 'En las vistas normal y compacta, si hay más de una cuenta.',
  "aj.separadas": "Cada cuenta en su propia ventana",
  "aj.separadas.ayuda": "Cada una se mueve por separado y tiene su propia vista.",
  'tray.vista.cuentas': 'Cuentas (todas a la vez)',
  'boton.vistaNormal': 'Volver a la vista normal',
  'plan.free': 'Gratis',
  'plan.titulo': 'Plan {plan}',
  'extra.etiqueta': 'Uso extra',
  'aj.seccion.semana': 'Cuota semanal',
  'aj.semana.aviso': 'Avisarme al llegar a',
  'aj.semana.activar': 'Activar el aviso de la semana',
  'err.umbralSemana': 'El aviso de la cuota semanal debe estar entre 50% y 99%.',
  "alerta.contexto.titulo": "Es buen momento para compactar",
  "alerta.contexto.cuerpo": "El chat «{chat}» lleva {porcentaje}% de su contexto. Escribe /compact en Claude Code para resumirlo.",
  "aj.seccion.contexto": "Ventana de contexto de Claude Code",
  "chats.sinNombre": "Chat sin nombre",
  "chats.titulo": "Ventana de contexto de Claude Code",
  "aj.contexto.mostrar": "Mostrar el contexto de cada chat",
  "aj.contexto.aviso": "Avisarme al llegar a",
  "aj.contexto.activar": "Recordarme compactar (y cada 10% más)",
  "aj.contexto.tamano": "Tamaño del contexto",
  "aj.contexto.auto": "Automático",
  "aj.contexto.ayuda": "Solo funciona si usas Claude Code en este mismo computador, y solo con una cuenta en Headroom. No ve los chats de claude.ai (en la web o en la app), ni los de otros equipos. Muestra los chats de las últimas 3 horas (hasta 5).",
  "err.umbralContexto": "El recordatorio del contexto debe estar entre 10% y 95%.",
  'alerta.semanaAviso.titulo': 'Vas alto en tu cuota semanal',
  'alerta.semanaAviso.cuerpo': 'Llevas {porcentaje}% de la cuota de la semana.',
  'alerta.semanaAviso.reinicia': ' Se reinicia {cuando}.',

  // ----- Mejoras: bandeja, avisos, reinicio, colores, historial -----
  'tray.versionNueva': "Actualizar a Headroom {version}",
  "tray.actualizando": "Descargando la actualización… {progreso}%",
  'tray.silencio': 'Silenciar avisos',
  'tray.silencio.hasta': 'Avisos silenciados hasta las {hora}',
  'tray.silencio.unaHora': 'Por 1 hora',
  'tray.silencio.manana': 'Hasta mañana',
  'tray.silencio.reactivar': 'Volver a activar los avisos',
  'alerta.version.titulo': 'Hay una versión nueva de Headroom',
  'alerta.version.cuerpo': "La versión {version} está disponible. Haz clic para actualizar.",
  'alerta.sesionRitmo.titulo': 'A este ritmo te quedarás sin sesión',
  'alerta.sesionRitmo.cuerpo': 'Llegarías al límite cerca de las {hora}, antes del reinicio de las {reinicio}.',
  'err.colores': 'Los colores elegidos no son válidos.',
  'tiempo.ahora': 'ahora',
  'tiempo.min': 'en {m} min',
  'tiempo.horas': 'en {h} h',
  'tiempo.horasMin': 'en {h} h {m} min',
  'tiempo.dias': 'en {d} d',
  'tiempo.diasHoras': 'en {d} d {h} h',
  'historial.7': '7 días',
  "historial.dia": "Hoy",
  "historial.diaVacio": "Todavía no hay lecturas de hoy. El gráfico se va llenando con cada consulta.",
  "historial.porDia": "Uso por día",
  "historial.diasVacio": "Todavía no hay días guardados. El gráfico se va llenando día a día.",
  "historial.limite": "tu límite",
  'historial.30': '30 días',
  'historial.dias': 'Días que se muestran',
  'historial.promedio': 'Promedio: {valor}% por día',
  'aj.reinicio': 'Mostrar el reinicio como',
  'aj.reinicio.relativo': 'Cuenta regresiva (en 2 h 15 min)',
  'aj.reinicio.hora': 'Hora (15:06)',
  'aj.colores': 'Colores',
  'aj.colores.acento': 'Acento',
  'aj.colores.bajo': 'Bajo',
  'aj.colores.medio': 'Medio',
  'aj.colores.alto': 'Alto',
  'aj.colores.restablecer': 'Restablecer',
  'aj.iconoDeColor': 'Ícono de la bandeja con el color de tu uso de hoy',
  'aj.sesion.ritmo': 'Avisarme si a este ritmo me quedaré sin sesión',
  'aj.atajo': 'Ctrl + Alt + C muestra u oculta el widget',
  'aj.actualizaciones': 'Avisarme cuando haya una versión nueva',
  "aj.resumenes": "Resumen de ayer y de la semana",
  "alerta.resumenDia.titulo": "Tu día de ayer",
  "alerta.resumenDia.cuerpo": "Ayer usaste {uso}% de tu cuota semanal (tu límite era {limite}%).",
  "alerta.resumenDia.pasado": "Ayer usaste {uso}% de tu cuota semanal: te pasaste de tu límite de {limite}%.",
  "alerta.resumenSemana.titulo": "Terminó tu semana",
  "alerta.resumenSemana.cuerpo": "Usaste {semana}% de tu cuota semanal.",
  "alerta.resumenSemana.dia": "Tu día más alto fue el {dia} ({uso}%).",
  "historial.horas": "Horas",
  "historial.horas.titulo": "A qué horas del día usas más",
  "horas.pico": "Pico {desde}–{hasta} h",
  "horas.vacio": "Aún no hay datos por hora: se va llenando con cada día de uso.",
  "horas.dias": "Promedio de {n} día(s)",
  "comp.arriba": "Vas {n} puntos por encima de la semana pasada a esta misma altura (ibas en {antes}%).",
  "comp.abajo": "Vas {n} puntos por debajo de la semana pasada a esta misma altura (ibas en {antes}%).",
  "comp.igual": "Vas casi igual que la semana pasada a esta misma altura (ibas en {antes}%).",
  "comp.aprox": "Es una estimación: será exacta desde la próxima semana.",
  "comp.corto.arriba": "▲ {n} pts más que la semana pasada",
  "comp.corto.abajo": "▼ {n} pts menos que la semana pasada",
  "comp.corto.igual": "= Igual que la semana pasada",
  "aj.copia.guardar": "Guardar copia…",
  "aj.copia.restaurar": "Restaurar copia…",
  "aj.copia.ayuda": "La copia guarda tus ajustes, cuentas e historial. No guarda tus sesiones: en otro computador tendrás que entrar de nuevo a cada cuenta.",
  "copia.guardar.titulo": "Guardar copia de seguridad",
  "copia.restaurar.titulo": "Restaurar copia de seguridad",
  "copia.filtro": "Copia de Headroom",
  "copia.guardada": "Listo: copia guardada.",
  "copia.invalida": "Ese archivo no es una copia de Headroom.",
  "copia.confirmar": "¿Restaurar la copia del {fecha} ({n} cuenta(s))?",
  "copia.confirmar.detalle": "Se reemplazan tus ajustes, cuentas e historial de ahora. Headroom se cerrará y se volverá a abrir.",
  "copia.confirmar.si": "Restaurar",
  "copia.confirmar.no": "Cancelar",
  "aj.seccion.copia": "Copia de seguridad",
};
