// es.js: todos los textos de la app en español (de Chile).
//
// Cada texto tiene una clave (ej. 'tray.salir'). Los trozos entre llaves, como {hoy}, se reemplazan por valores
// al mostrar el texto. Para agregar un idioma nuevo: copiar este archivo (por ejemplo a "pt.js"), traducir los
// textos SIN cambiar las claves ni las {llaves}, y anotar el idioma en idiomas.js.

module.exports = {
  // ----- Datos del idioma -----
  'meta.nombre': 'Español',
  'meta.locale': 'es-CL',          // para escribir números (12,5) y nombres de días
  'meta.csvSeparador': ';',        // el Excel en español separa las columnas con punto y coma

  // ----- General -----
  'app.nombre': 'Cupo',
  'hoy.etiqueta': 'Hoy',
  'sesion.etiqueta': 'Sesión 5 h',
  'semana.etiqueta': 'Semana',
  'reinicio.prefijo': 'Reinicio: ',
  'hoy.de': '{hoy}% de {limite}%',
  'lectura.cargando': 'Leyendo uso…',
  'sesion.sinActividad': 'sin actividad',

  // ----- Errores al leer el uso -----
  'error.sinConexion': 'Sin conexión a claude.ai',
  'error.formato': 'Datos de claude.ai cambiaron',
  'error.generico': 'No se pudo leer el uso',

  // ----- Inicio de sesión -----
  'login.sinSesion': 'No has iniciado sesión',
  'login.expirada': 'Tu sesión expiró',
  'login.iniciar': 'Iniciar sesión',
  'login.reentrar': 'Volver a entrar',
  'login.titulo': 'Iniciar sesión en Claude',

  // ----- Paneles -----
  'panel.historial': 'Últimos 7 días',
  'panel.desglose': 'Desglose de la semana',
  'panel.proyeccion': 'Proyección',
  'panel.ajustes': 'Ajustes',
  'panel.detalle': 'Detalle',
  'panel.cerrar': 'Cerrar',
  'panel.cerrarAria': 'Cerrar el panel',

  // ----- Botones de la tarjeta -----
  'boton.historial': 'Uso de los últimos 7 días',
  'boton.historialAria': 'Ver el uso de los últimos 7 días',
  'boton.desglose': 'Desglose de la semana por producto',
  'boton.desgloseAria': 'Ver el desglose de la semana por producto',
  'boton.proyeccion': 'Proyección: a este ritmo...',
  'boton.proyeccionAria': 'Ver la proyección de uso',
  'boton.ajustes': 'Ajustes',
  'boton.ajustesAria': 'Abrir los ajustes',
  'boton.compacto': 'Vista compacta (una línea)',
  'boton.compactoAria': 'Cambiar entre la vista compacta y la normal',
  'boton.completo': 'Vista completa (todo a la vez)',
  'boton.completoAria': 'Cambiar entre la vista completa y la normal',
  'boton.orientacion': 'Cambiar la disposición (vertical / horizontal)',
  'boton.orientacionAria': 'Cambiar entre la disposición vertical y la horizontal',

  // ----- Historial -----
  'historial.hoy': 'hoy',
  'historial.limiteDia': 'Límite de ese día: {limite}%',

  // ----- Nombres de los productos (el desglose) -----
  'producto.claude_code': 'Claude Code',
  'producto.chat': 'Chats',
  'producto.cowork': 'Cowork',
  'producto.other': 'Otros',

  // ----- Desglose -----
  'desglose.sinDatos': 'Todavía no hay datos. Espera a la primera lectura.',
  'desglose.sinDesglose': 'claude.ai no entregó el desglose en esta lectura.',
  'desglose.nota': 'Reparto de lo que usaste esta semana ({semana}% de tu cuota).',

  // ----- Proyección -----
  'proy.dia.yaLlegaste': 'Ya llegaste a tu límite de hoy',
  'proy.dia.yaLlegaste.detalle': 'Mejor ir con calma el resto del día.',
  'proy.dia.llegaras': 'Llegarías a tu límite hacia las {hora}',
  'proy.dia.llegaras.detalle': 'A este ritmo, antes de medianoche.',
  'proy.dia.noLlegaras': 'No llegarías a tu límite hoy',
  'proy.dia.noLlegaras.detalle': 'Terminarías el día en ~{fin}%.',
  'proy.dia.sinUso': 'Todavía no has usado nada hoy',
  'proy.dia.sinUso.detalle': 'Con este ritmo no llegarías al límite.',
  'proy.dia.sinDatos': 'Aún es pronto para estimar',
  'proy.dia.sinDatos.detalle': 'Falta al menos media hora de medición.',
  'proy.semana.yaLlegaste': 'Ya agotaste tu cuota semanal',
  'proy.semana.yaLlegaste.detalle': 'Se reinicia {reinicio}.',
  'proy.semana.llegaras': 'Llegarías al 100% el {cuando}',
  'proy.semana.llegaras.detalle': 'Antes del reinicio ({reinicio}).',
  'proy.semana.noLlegaras': 'No agotarías tu cuota esta semana',
  'proy.semana.noLlegaras.detalle': 'Llegarías a ~{fin}% antes del reinicio.',
  'proy.semana.sinUso': 'Todavía no has usado nada esta semana',
  'proy.semana.sinUso.detalle': 'No hay nada que proyectar aún.',
  'proy.semana.sinDatos': 'Aún es pronto para estimar',
  'proy.semana.sinDatos.detalle': 'La semana acaba de empezar.',
  'proy.sinDatos': 'Todavía no hay datos',
  'proy.sinDatos.detalle': 'Espera a la primera lectura.',
  'proy.nota': 'Estimaciones según tu ritmo de uso hasta ahora.',

  // ----- Ajustes -----
  'aj.seccion.vista': 'Vista',
  'aj.vista': 'Vista',
  'aj.vista.normal': 'Normal',
  'aj.vista.compacto': 'Compacto (una sola línea)',
  'aj.vista.completo': 'Completo (todo a la vez)',
  'aj.disposicion': 'Disposición',
  'aj.disposicion.vertical': 'Vertical (barras apiladas)',
  'aj.disposicion.horizontal': 'Horizontal (lado a lado)',
  'aj.disposicion.ayuda': 'La disposición vale para la vista normal. La vista completa siempre es ancha.',
  'aj.seccion.escala': 'Escala de la interfaz',
  'aj.escala.rapidos': 'Tamaños rápidos',
  'aj.escala.ayuda': 'Agranda o achica todo el widget al instante. También: Ctrl + rueda del mouse, o Ctrl + / Ctrl − (y Ctrl 0 vuelve al 100%).',
  'aj.seccion.apariencia': 'Apariencia',
  'aj.tema': 'Tema',
  'aj.tema.oscuro': 'Oscuro',
  'aj.tema.claro': 'Claro',
  'aj.tema.auto': 'Automático (como Windows)',
  'aj.transparencia': 'Transparencia del fondo',
  'aj.siempreEncima': 'Siempre encima de otras ventanas',
  'aj.idioma': 'Idioma',
  'aj.idioma.auto': 'Automático (como Windows)',
  'aj.seccion.limite': 'Límite diario',
  'aj.limite': 'Límite',
  'aj.aviso': 'Aviso previo',
  'aj.limite.ayuda': 'Cuánto de tu cuota semanal quieres usar como máximo al día. El aviso debe ser menor que el límite.',
  'aj.limitesPorDia': 'Un límite distinto para cada día',
  'aj.limitesPorDia.ayuda': 'El aviso previo se ajusta solo, en la misma proporción.',
  'aj.dia.0': 'Lu',
  'aj.dia.1': 'Ma',
  'aj.dia.2': 'Mi',
  'aj.dia.3': 'Ju',
  'aj.dia.4': 'Vi',
  'aj.dia.5': 'Sá',
  'aj.dia.6': 'Do',
  'aj.dia.aria': 'Límite del día {dia}',
  'aj.seccion.sesion': 'Sesión de 5 horas',
  'aj.sesion.aviso': 'Avisarme al llegar a',
  'aj.sesion.activar': 'Activar los avisos de la sesión',
  'aj.seccion.consulta': 'Consulta',
  'aj.intervalo': 'Consultar el uso cada',
  'aj.intervalo.minutos': '{n} minutos',
  'aj.intervalo.hora': '1 hora',
  'aj.intervalo.ayuda': 'El mínimo es 5 minutos.',
  'aj.seccion.sistema': 'Sistema y datos',
  'aj.arranque': 'Abrir el widget al iniciar Windows',
  'aj.exportar': 'Exportar historial (CSV)…',
  'aj.guardar': 'Guardar',
  'aj.guardado': 'Guardado ✓',
  'aj.exportado': 'Listo: se guardaron {n} día(s).',

  // ----- Errores de validación de los ajustes -----
  'err.limite': 'El límite diario debe estar entre 1% y 100%.',
  'err.avisoMinimo': 'El aviso previo debe ser de al menos 1%.',
  'err.avisoMenor': 'El aviso previo debe ser menor que el límite diario.',
  'err.intervalo': 'El intervalo de consulta no es válido.',
  'err.umbralSesion': 'El aviso de la sesión de 5 horas debe estar entre 50% y 99%.',
  'err.opcion': 'Hay una opción con un valor no válido.',
  'err.vista': 'La vista elegida no es válida.',
  'err.disposicion': 'La disposición elegida no es válida.',
  'err.tema': 'El tema elegido no es válido.',
  'err.idioma': 'El idioma elegido no es válido.',
  'err.transparencia': 'La transparencia debe dejar el widget entre 40% y 100% visible.',
  'err.escala': 'El tamaño debe estar entre {min}% y {max}%.',
  'err.limitesSiete': 'Los límites por día deben ser siete valores, de lunes a domingo.',
  'err.limiteDia': 'El límite de cada día debe estar entre 1% y 100%.',

  // ----- Menú de la bandeja (junto al reloj) -----
  'tray.actualizado': 'Cupo · actualizado {hora}',
  'tray.actualizar': 'Actualizar',
  'tray.mostrarOcultar': 'Mostrar / Ocultar',
  'tray.siempreEncima': 'Siempre encima',
  'tray.historial': 'Historial de 7 días',
  'tray.desglose': 'Desglose de la semana',
  'tray.proyeccion': 'Proyección',
  'tray.vista': 'Vista',
  'tray.vista.normal': 'Normal',
  'tray.vista.compacto': 'Compacto (una línea)',
  'tray.vista.completo': 'Completo (todo a la vez)',
  'tray.disposicion.vertical': 'Disposición vertical',
  'tray.disposicion.horizontal': 'Disposición horizontal',
  'tray.exportar': 'Exportar historial (CSV)…',
  'tray.ajustes': 'Ajustes',
  'tray.cerrarSesion': 'Cerrar sesión',
  'tray.salir': 'Salir',

  // ----- Exportar el historial -----
  'exportar.titulo': 'Exportar historial de uso',
  'exportar.filtro': 'Archivo CSV (se abre en Excel)',
  'exportar.nombreArchivo': 'historial-uso-claude-{fecha}.csv',
  'exportar.vacio': 'Todavía no hay días registrados para exportar.',
  'exportar.error': 'No se pudo guardar el archivo: {mensaje}',
  'csv.fecha': 'Fecha',
  'csv.uso': 'Uso del día (%)',
  'csv.limite': 'Límite del día (%)',
  'csv.supero': '¿Superó el límite?',
  'csv.si': 'Sí',
  'csv.no': 'No',

  // ----- Notificaciones de Windows -----
  'alerta.limite.titulo': 'Llegaste a tu límite diario de Claude',
  'alerta.aviso.titulo': 'Te acercas a tu límite diario de Claude',
  'alerta.diario.cuerpo': 'Hoy llevas {hoy}% de tu cuota semanal (límite: {limite}%).',
  'alerta.sesionAviso.titulo': 'Te queda poco de tu sesión de 5 horas',
  'alerta.sesionAviso.cuerpo': 'Llevas {porcentaje}% de la sesión.',
  'alerta.sesionReinicia': ' Se reinicia a las {hora}.',
  'alerta.sesionLimite.titulo': 'Llegaste al límite de tu sesión de 5 horas',
  'alerta.sesionLimite.conHora': 'Podrás volver a usar Claude a las {hora}.',
  'alerta.sesionLimite.sinHora': 'Tendrás que esperar a que se reinicie la sesión.',
  'alerta.sesionReiniciada.titulo': 'Tu sesión de 5 horas se reinició',
  'alerta.sesionReiniciada.cuerpo': 'Ya puedes volver a usar Claude.',
  'alerta.exportado.titulo': 'Historial exportado',
  'alerta.exportado.uno': 'Se guardó 1 día en: {ruta}',
  'alerta.exportado.varios': 'Se guardaron {n} días en: {ruta}',
  'alerta.formato.titulo': 'El widget no puede leer tu uso de Claude',
  'alerta.formato.cuerpo': 'Parece que claude.ai cambió su página. Abre Claude Code en la carpeta del proyecto y pídele que revise src/uso.js.',

  // ----- Varias cuentas -----
  'cuentas.principal': 'Principal',
  'login.tituloCuenta': 'Iniciar sesión en Claude — {nombre}',
  'panel.cuentas': 'Cuentas',
  'boton.cuenta': 'Cuenta: {nombre} (clic para ver tus cuentas)',
  'cuentas.usar': 'Mostrar esta cuenta',
  'cuentas.nombre': 'Nombre de la cuenta',
  'cuentas.estado.conectado': 'Sesión iniciada',
  'cuentas.estado.sinSesion': 'Sin sesión',
  'cuentas.estado.expirada': 'Sesión expirada',
  'cuentas.cerrarSesion': 'Cerrar sesión',
  'cuentas.iniciarSesion': 'Iniciar sesión',
  'cuentas.eliminar': 'Eliminar esta cuenta',
  'cuentas.eliminarSeguro': '¿Seguro?',
  'cuentas.nueva': 'Nombre de la cuenta nueva',
  'cuentas.agregar': 'Agregar',
  'cuentas.ayuda': 'Cerrar sesión conserva el historial y los límites: sirve para entrar con otra cuenta de Claude en el mismo lugar. Eliminar lo borra todo.',
  'cuentas.err.nombre': 'Escribe un nombre para la cuenta.',
  'cuentas.err.maximo': 'Puedes tener hasta {n} cuentas.',
  'aj.seccion.limiteDe': 'Límite diario · {nombre}',
  'resumen.sinSesion': 'Sin sesión',
  'tray.cuenta': 'Cuenta',
  'tray.cuentasAdministrar': 'Administrar cuentas…',
  'tray.cerrarSesionDe': 'Cerrar sesión de {nombre}',
  'aj.vista.cuentas': 'Cuentas (todas a la vez)',
  'aj.todas': 'Mostrar todas las cuentas a la vez',
  'aj.todas.ayuda': 'En la vista normal y la compacta, cuando hay más de una cuenta.',
  'tray.vista.cuentas': 'Cuentas (todas a la vez)',
  'boton.vistaNormal': 'Volver a la vista normal',
  'plan.free': 'Gratis',
  'plan.titulo': 'Plan {plan}',
};
