// fr.js : tous les textes de l'application en français.
//
// Chaque texte a une clé (ex. 'tray.salir'), les mêmes que dans es.js. Les morceaux entre accolades, comme {hoy},
// sont remplacés par des valeurs à l'affichage : ils doivent rester exactement tels quels.

module.exports = {
  // ----- Données de la langue -----
  "meta.nombre": "Français",
  "meta.locale": "fr-FR",
  "meta.csvSeparador": ";",

  // ----- Général -----
  "app.nombre": "Cupo",
  "hoy.etiqueta": "Aujourd'hui",
  "sesion.etiqueta": "Session 5 h",
  "semana.etiqueta": "Semaine",
  "reinicio.prefijo": "Réinit. : ",
  "hoy.de": "{hoy} % sur {limite} %",
  "lectura.cargando": "Lecture de l'utilisation…",
  "sesion.sinActividad": "aucune activité",

  // ----- Erreurs de lecture -----
  "error.sinConexion": "Impossible de joindre claude.ai",
  "error.formato": "Les données de claude.ai ont changé",
  "error.generico": "Lecture de l'utilisation impossible",

  // ----- Connexion -----
  "login.sinSesion": "Vous n'êtes pas connecté",
  "login.expirada": "Votre session a expiré",
  "login.iniciar": "Se connecter",
  "login.reentrar": "Se reconnecter",
  "login.titulo": "Se connecter à Claude",

  // ----- Panneaux -----
  "panel.historial": "Historique",
  "panel.desglose": "Répartition de la semaine",
  "panel.proyeccion": "Projection",
  "panel.ajustes": "Réglages",
  "panel.detalle": "Détails",
  "panel.cerrar": "Fermer",
  "panel.cerrarAria": "Fermer le panneau",

  // ----- Boutons de la carte -----
  "boton.historial": "Historique d'utilisation",
  "boton.historialAria": "Voir l'historique d'utilisation",
  "boton.desglose": "Répartition de la semaine par produit",
  "boton.desgloseAria": "Voir la répartition de la semaine par produit",
  "boton.proyeccion": "Projection : à ce rythme...",
  "boton.proyeccionAria": "Voir la projection d'utilisation",
  "boton.ajustes": "Réglages",
  "boton.ajustesAria": "Ouvrir les réglages",
  "boton.compacto": "Vue compacte (une ligne)",
  "boton.compactoAria": "Basculer entre la vue compacte et la vue normale",
  "boton.completo": "Vue complète (tout à la fois)",
  "boton.completoAria": "Basculer entre la vue complète et la vue normale",
  "boton.orientacion": "Changer la disposition (verticale / horizontale)",
  "boton.orientacionAria": "Basculer entre la disposition verticale et horizontale",

  // ----- Historique -----
  "historial.hoy": "auj.",
  "historial.limiteDia": "Limite de ce jour : {limite} %",

  // ----- Noms des produits -----
  "producto.claude_code": "Claude Code",
  "producto.chat": "Chats",
  "producto.cowork": "Cowork",
  "producto.other": "Autres",

  // ----- Répartition -----
  "desglose.sinDatos": "Pas encore de données. Attendez la première lecture.",
  "desglose.sinDesglose": "claude.ai n'a pas fourni la répartition lors de cette lecture.",
  "desglose.nota": "Répartition de ce que vous avez utilisé cette semaine ({semana} % de votre quota).",

  // ----- Projection -----
  "proy.dia.yaLlegaste": "Vous avez déjà atteint la limite du jour",
  "proy.dia.yaLlegaste.detalle": "Mieux vaut lever le pied pour le reste de la journée.",
  "proy.dia.llegaras": "Vous atteindriez la limite vers {hora}",
  "proy.dia.llegaras.detalle": "À ce rythme, avant minuit.",
  "proy.dia.noLlegaras": "Vous n'atteindriez pas la limite aujourd'hui",
  "proy.dia.noLlegaras.detalle": "Vous finiriez la journée à ~{fin} %.",
  "proy.dia.sinUso": "Vous n'avez encore rien utilisé aujourd'hui",
  "proy.dia.sinUso.detalle": "À ce rythme, vous n'atteindriez pas la limite.",
  "proy.dia.sinDatos": "Il est trop tôt pour estimer",
  "proy.dia.sinDatos.detalle": "Il faut au moins une demi-heure de mesure.",
  "proy.semana.yaLlegaste": "Vous avez épuisé votre quota hebdomadaire",
  "proy.semana.yaLlegaste.detalle": "Il se réinitialise {reinicio}.",
  "proy.semana.llegaras": "Vous atteindriez 100 % {cuando}",
  "proy.semana.llegaras.detalle": "Avant la réinitialisation ({reinicio}).",
  "proy.semana.noLlegaras": "Vous n'épuiseriez pas votre quota cette semaine",
  "proy.semana.noLlegaras.detalle": "Vous atteindriez ~{fin} % avant la réinitialisation.",
  "proy.semana.sinUso": "Vous n'avez encore rien utilisé cette semaine",
  "proy.semana.sinUso.detalle": "Rien à projeter pour l'instant.",
  "proy.semana.sinDatos": "Il est trop tôt pour estimer",
  "proy.semana.sinDatos.detalle": "La semaine vient de commencer.",
  "proy.sinDatos": "Pas encore de données",
  "proy.sinDatos.detalle": "Attendez la première lecture.",
  "proy.nota": "Estimations selon votre rythme d'utilisation jusqu'ici.",

  // ----- Réglages -----
  "aj.seccion.vista": "Affichage",
  "aj.vista": "Vue",
  "aj.vista.normal": "Normale",
  "aj.vista.compacto": "Compacte (une seule ligne)",
  "aj.vista.completo": "Complète (tout à la fois)",
  "aj.disposicion": "Disposition",
  "aj.disposicion.vertical": "Verticale (barres empilées)",
  "aj.disposicion.horizontal": "Horizontale (côte à côte)",
  "aj.disposicion.ayuda": "S'applique à la vue normale ; la vue complète est toujours large.",
  "aj.seccion.escala": "Échelle de l'interface",
  "aj.escala.rapidos": "Tailles rapides",
  "aj.escala.ayuda": "Agrandit ou réduit tout instantanément. Aussi : Ctrl + molette (Ctrl 0 revient à 100 %).",
  "aj.seccion.apariencia": "Apparence",
  "aj.tema": "Thème",
  "aj.tema.oscuro": "Sombre",
  "aj.tema.claro": "Clair",
  "aj.tema.auto": "Automatique (comme Windows)",
  "aj.transparencia": "Transparence du fond",
  "aj.siempreEncima": "Toujours au-dessus des autres fenêtres",
  "aj.idioma": "Langue",
  "aj.idioma.auto": "Automatique (comme Windows)",
  "aj.seccion.limite": "Limite quotidienne",
  "aj.limite": "Limite",
  "aj.aviso": "Alerte préalable",
  "aj.limite.ayuda": "La part maximale de votre quota hebdomadaire à utiliser par jour. L'alerte doit être inférieure à la limite.",
  "aj.limitesPorDia": "Une limite différente pour chaque jour",
  "aj.limitesPorDia.ayuda": "L'alerte préalable s'ajuste toute seule, dans la même proportion.",
  "aj.dia.0": "Lu",
  "aj.dia.1": "Ma",
  "aj.dia.2": "Me",
  "aj.dia.3": "Je",
  "aj.dia.4": "Ve",
  "aj.dia.5": "Sa",
  "aj.dia.6": "Di",
  "aj.dia.aria": "Limite du {dia}",
  "aj.seccion.sesion": "Session de 5 heures",
  "aj.sesion.aviso": "M'alerter à",
  "aj.sesion.activar": "Activer les alertes de session",
  "aj.seccion.consulta": "Actualisation",
  "aj.intervalo": "Vérifier l'utilisation toutes les",
  "aj.intervalo.minutos": "{n} minutes",
  "aj.intervalo.hora": "1 heure",
  "aj.intervalo.ayuda": "Le minimum est de 5 minutes.",
  "aj.seccion.sistema": "Système et données",
  "aj.arranque": "Ouvrir le widget au démarrage de Windows",
  "aj.exportar": "Exporter l'historique (CSV)…",
  "aj.guardar": "Enregistrer",
  "aj.guardado": "Enregistré ✓",
  "aj.exportado": "Terminé : {n} jour(s) enregistré(s).",

  // ----- Erreurs des réglages -----
  "err.limite": "La limite quotidienne doit être comprise entre 1 % et 100 %.",
  "err.avisoMinimo": "L'alerte préalable doit être d'au moins 1 %.",
  "err.avisoMenor": "L'alerte préalable doit être inférieure à la limite quotidienne.",
  "err.intervalo": "L'intervalle d'actualisation n'est pas valide.",
  "err.umbralSesion": "L'alerte de la session de 5 heures doit être comprise entre 50 % et 99 %.",
  "err.opcion": "Une option a une valeur non valide.",
  "err.vista": "La vue choisie n'est pas valide.",
  "err.disposicion": "La disposition choisie n'est pas valide.",
  "err.tema": "Le thème choisi n'est pas valide.",
  "err.idioma": "La langue choisie n'est pas valide.",
  "err.transparencia": "La transparence doit laisser le widget visible entre 40 % et 100 %.",
  "err.escala": "L'échelle doit être comprise entre {min} % et {max} %.",
  "err.limitesSiete": "Les limites par jour doivent être sept valeurs, du lundi au dimanche.",
  "err.limiteDia": "La limite de chaque jour doit être comprise entre 1 % et 100 %.",

  // ----- Menu de la zone de notification -----
  "tray.actualizado": "Cupo · mis à jour à {hora}",
  "tray.actualizar": "Actualiser",
  "tray.mostrarOcultar": "Afficher / Masquer",
  "tray.siempreEncima": "Toujours au-dessus",
  "tray.historial": "Historique",
  "tray.desglose": "Répartition de la semaine",
  "tray.proyeccion": "Projection",
  "tray.vista": "Vue",
  "tray.vista.normal": "Normale",
  "tray.vista.compacto": "Compacte (une ligne)",
  "tray.vista.completo": "Complète (tout à la fois)",
  "tray.disposicion.vertical": "Disposition verticale",
  "tray.disposicion.horizontal": "Disposition horizontale",
  "tray.exportar": "Exporter l'historique (CSV)…",
  "tray.ajustes": "Réglages",
  "tray.cerrarSesion": "Se déconnecter",
  "tray.salir": "Quitter",

  // ----- Exporter l'historique -----
  "exportar.titulo": "Exporter l'historique d'utilisation",
  "exportar.filtro": "Fichier CSV (s'ouvre dans Excel)",
  "exportar.nombreArchivo": "historique-utilisation-claude-{fecha}.csv",
  "exportar.vacio": "Il n'y a pas encore de jours enregistrés à exporter.",
  "exportar.error": "Impossible d'enregistrer le fichier : {mensaje}",
  "csv.fecha": "Date",
  "csv.uso": "Utilisation du jour (%)",
  "csv.limite": "Limite du jour (%)",
  "csv.supero": "Limite dépassée ?",
  "csv.si": "Oui",
  "csv.no": "Non",

  // ----- Notifications Windows -----
  "alerta.limite.titulo": "Vous avez atteint votre limite quotidienne de Claude",
  "alerta.aviso.titulo": "Vous approchez de votre limite quotidienne de Claude",
  "alerta.diario.cuerpo": "Aujourd'hui vous avez utilisé {hoy} % de votre quota hebdomadaire (limite : {limite} %).",
  "alerta.sesionAviso.titulo": "Votre session de 5 heures touche à sa fin",
  "alerta.sesionAviso.cuerpo": "Vous avez utilisé {porcentaje} % de la session.",
  "alerta.sesionReinicia": " Elle se réinitialise à {hora}.",
  "alerta.sesionLimite.titulo": "Vous avez atteint la limite de la session de 5 heures",
  "alerta.sesionLimite.conHora": "Vous pourrez utiliser Claude à nouveau à {hora}.",
  "alerta.sesionLimite.sinHora": "Il faudra attendre la réinitialisation de la session.",
  "alerta.sesionReiniciada.titulo": "Votre session de 5 heures s'est réinitialisée",
  "alerta.sesionReiniciada.cuerpo": "Vous pouvez utiliser Claude à nouveau.",
  "alerta.exportado.titulo": "Historique exporté",
  "alerta.exportado.uno": "1 jour enregistré dans : {ruta}",
  "alerta.exportado.varios": "{n} jours enregistrés dans : {ruta}",
  "alerta.formato.titulo": "Le widget ne parvient pas à lire votre utilisation de Claude",
  "alerta.formato.cuerpo": "On dirait que claude.ai a changé sa page. Ouvrez Claude Code dans le dossier du projet et demandez-lui de vérifier src/uso.js.",

  // ----- Plusieurs comptes -----
  "cuentas.principal": "Principal",
  "login.tituloCuenta": "Se connecter à Claude — {nombre}",
  "panel.cuentas": "Comptes",
  "boton.cuenta": "Compte : {nombre} (cliquez pour voir vos comptes)",
  "cuentas.usar": "Afficher ce compte",
  "cuentas.nombre": "Nom du compte",
  "cuentas.estado.conectado": "Connecté",
  "cuentas.estado.sinSesion": "Non connecté",
  "cuentas.estado.expirada": "Session expirée",
  "cuentas.cerrarSesion": "Déconnexion",
  "cuentas.iniciarSesion": "Connexion",
  "cuentas.eliminar": "Supprimer ce compte",
  "cuentas.eliminarSeguro": "Sûr ?",
  "cuentas.nueva": "Nom du nouveau compte",
  "cuentas.agregar": "Ajouter",
  "cuentas.ayuda": "Se déconnecter garde l'historique et les limites : utile pour se connecter avec un autre compte Claude au même endroit. Supprimer efface tout.",
  "cuentas.err.nombre": "Saisissez un nom pour le compte.",
  "cuentas.err.maximo": "Vous pouvez avoir jusqu'à {n} comptes.",
  "aj.seccion.limiteDe": "Limite quotidienne · {nombre}",
  "resumen.sinSesion": "Non connecté",
  "tray.cuenta": "Compte",
  "tray.cuentasAdministrar": "Gérer les comptes…",
  "tray.cerrarSesionDe": "Déconnecter {nombre}",
  "aj.vista.cuentas": "Comptes (tous à la fois)",
  "aj.todas": "Afficher tous les comptes à la fois",
  "aj.todas.ayuda": "Dans les vues normale et compacte, s'il y a plus d'un compte.",
  "tray.vista.cuentas": "Comptes (tous à la fois)",
  "boton.vistaNormal": "Revenir à la vue normale",
  "plan.free": "Gratuit",
  "plan.titulo": "Forfait {plan}",
  "extra.etiqueta": "Usage suppl.",
  "aj.seccion.semana": "Quota hebdomadaire",
  "aj.semana.aviso": "M'alerter à",
  "aj.semana.activar": "Activer l'alerte de la semaine",
  "err.umbralSemana": "L'alerte du quota hebdomadaire doit être comprise entre 50 % et 99 %.",
  "alerta.semanaAviso.titulo": "Votre quota hebdomadaire est élevé",
  "alerta.semanaAviso.cuerpo": "Vous avez utilisé {porcentaje} % du quota de la semaine.",
  "alerta.semanaAviso.reinicia": " Il se réinitialise {cuando}.",

  // ----- Améliorations : zone de notification, alertes, réinitialisation, couleurs, historique -----
  "tray.versionNueva": "Télécharger Cupo {version}…",
  "tray.silencio": "Désactiver les alertes",
  "tray.silencio.hasta": "Alertes désactivées jusqu'à {hora}",
  "tray.silencio.unaHora": "Pendant 1 heure",
  "tray.silencio.manana": "Jusqu'à demain",
  "tray.silencio.reactivar": "Réactiver les alertes",
  "alerta.version.titulo": "Une nouvelle version de Cupo est disponible",
  "alerta.version.cuerpo": "La version {version} est sortie. Cliquez pour la télécharger.",
  "alerta.sesionRitmo.titulo": "À ce rythme, votre session sera épuisée",
  "alerta.sesionRitmo.cuerpo": "Vous atteindriez la limite vers {hora}, avant la réinitialisation à {reinicio}.",
  "err.colores": "Les couleurs choisies ne sont pas valides.",
  "tiempo.ahora": "maintenant",
  "tiempo.min": "dans {m} min",
  "tiempo.horas": "dans {h} h",
  "tiempo.horasMin": "dans {h} h {m} min",
  "tiempo.dias": "dans {d} j",
  "tiempo.diasHoras": "dans {d} j {h} h",
  "historial.7": "7 jours",
  "historial.30": "30 jours",
  "historial.dias": "Jours affichés",
  "historial.promedio": "Moyenne : {valor} % par jour",
  "aj.reinicio": "Afficher la réinitialisation",
  "aj.reinicio.relativo": "Compte à rebours (dans 2 h 15 min)",
  "aj.reinicio.hora": "Heure (15:06)",
  "aj.colores": "Couleurs",
  "aj.colores.acento": "Accent",
  "aj.colores.bajo": "Bas",
  "aj.colores.medio": "Moyen",
  "aj.colores.alto": "Élevé",
  "aj.colores.restablecer": "Rétablir",
  "aj.iconoDeColor": "Icône de notification colorée selon l'utilisation du jour",
  "aj.sesion.ritmo": "M'alerter si, à ce rythme, ma session va s'épuiser",
  "aj.atajo": "Ctrl + Alt + C affiche ou masque le widget",
  "aj.actualizaciones": "Me prévenir quand une nouvelle version sort",
};
