// fr.js : tous les textes de l'application en français.
//
// Chaque texte a une clé (ex. 'tray.salir'), les mêmes que dans es.js. Les morceaux entre accolades, comme {hoy},
// sont remplacés par des valeurs à l'affichage : ils doivent rester exactement tels quels.

module.exports = {
  // ----- Données de la langue -----
  "meta.nombre": "Français",
  "meta.locale": "fr-FR",
  "meta.csvSeparador": ";",

  // ----- Général -----
  "app.nombre": "Headroom",
  "hoy.etiqueta": "Aujourd'hui",
  "sesion.etiqueta": "Session 5 h",
  "semana.etiqueta": "Semaine",
  "reinicio.prefijo": "Réinit. : ",
  "hoy.de": "{hoy} % sur {limite} %",
  "lectura.cargando": "Lecture de l'utilisation…",
  "sesion.sinActividad": "aucune activité",

  // ----- Erreurs de lecture -----
  "error.sinConexion": "Impossible de joindre claude.ai",
  "error.formato": "Les données de claude.ai ont changé",
  "error.generico": "Lecture de l'utilisation impossible",

  // ----- Connexion -----
  "login.sinSesion": "Vous n'êtes pas connecté",
  "login.expirada": "Votre session a expiré",
  "login.iniciar": "Se connecter",
  "login.reentrar": "Se reconnecter",
  "login.titulo": "Se connecter à Claude",

  // ----- Panneaux -----
  "panel.historial": "Historique",
  "panel.desglose": "Répartition de la semaine",
  "panel.productos": "Utilisation par produit",
  "productos.ver": "Au fil du temps ›",
  "productos.semana": "Cette semaine",
  "productos.semanas": "Semaines",
  "productos.estaSemana": "en cours",
  "productos.semanasVacio": "Aucune semaine enregistrée. À chaque réinitialisation de votre forfait, une s’ajoute.",
  "productos.nota": "En % de votre quota hebdomadaire : ce que chaque produit a utilisé.",
  "productos.vacio": "Pas encore de jours avec le détail par produit. Il se remplit jour après jour.",
  "panel.proyeccion": "Projection",
  "panel.ajustes": "Réglages",
  "panel.detalle": "Détails",
  "panel.cerrar": "Fermer",
  "parte.separar": "Ouvrir dans sa propre fenêtre",
  "parte.juntar": "Revenir au widget",
  "parte.todas": "Tous les comptes",
  "panel.cerrarAria": "Fermer le panneau",

  // ----- Boutons de la carte -----
  "boton.historial": "Historique d'utilisation",
  "boton.historialAria": "Voir l'historique d'utilisation",
  "boton.desglose": "Répartition de la semaine par produit",
  "boton.desgloseAria": "Voir la répartition de la semaine par produit",
  "boton.proyeccion": "Projection : à ce rythme...",
  "boton.proyeccionAria": "Voir la projection d'utilisation",
  "boton.ajustes": "Réglages",
  "boton.ajustesAria": "Ouvrir les réglages",
  "boton.compacto": "Vue compacte (une ligne)",
  "boton.compactoAria": "Basculer entre la vue compacte et la vue normale",
  "boton.completo": "Vue complète (tout à la fois)",
  "boton.completoAria": "Basculer entre la vue complète et la vue normale",
  "boton.orientacion": "Changer la disposition (verticale / horizontale)",
  "boton.orientacionAria": "Basculer entre la disposition verticale et horizontale",

  // ----- Historique -----
  "historial.hoy": "auj.",
  "historial.limiteDia": "Limite de ce jour : {limite} %",

  // ----- Noms des produits -----
  "producto.claude_code": "Claude Code",
  "producto.chat": "Chats",
  "producto.cowork": "Cowork",
  "producto.other": "Autres",

  // ----- Répartition -----
  "desglose.sinDatos": "Pas encore de données. Attendez la première lecture.",
  "desglose.sinDesglose": "claude.ai n'a pas fourni la répartition lors de cette lecture.",
  "desglose.nota": "Répartition de ce que vous avez utilisé cette semaine ({semana} % de votre quota).",
  "desglose.notaVarias": "Répartition de l’utilisation de chaque compte cette semaine (à droite, son % du quota).",

  // ----- Projection -----
  "proy.dia.yaLlegaste": "Vous avez déjà atteint la limite du jour",
  "proy.dia.yaLlegaste.detalle": "Mieux vaut lever le pied pour le reste de la journée.",
  "proy.dia.llegaras": "Vous atteindriez la limite vers {hora}",
  "proy.dia.llegaras.detalle": "À ce rythme, avant minuit.",
  "proy.dia.noLlegaras": "Vous n'atteindriez pas la limite aujourd'hui",
  "proy.dia.noLlegaras.detalle": "Vous finiriez la journée à ~{fin} %.",
  "proy.dia.sinUso": "Vous n'avez encore rien utilisé aujourd'hui",
  "proy.dia.sinUso.detalle": "À ce rythme, vous n'atteindriez pas la limite.",
  "proy.dia.sinDatos": "Il est trop tôt pour estimer",
  "proy.dia.sinDatos.detalle": "Il faut au moins une demi-heure de mesure.",
  "proy.semana.yaLlegaste": "Vous avez épuisé votre quota hebdomadaire",
  "proy.semana.yaLlegaste.detalle": "Il se réinitialise {reinicio}.",
  "proy.semana.llegaras": "Vous atteindriez 100 % {cuando}",
  "proy.semana.llegaras.detalle": "Avant la réinitialisation ({reinicio}).",
  "proy.semana.noLlegaras": "Vous n'épuiseriez pas votre quota cette semaine",
  "proy.semana.noLlegaras.detalle": "Vous atteindriez ~{fin} % avant la réinitialisation.",
  "proy.semana.sinUso": "Vous n'avez encore rien utilisé cette semaine",
  "proy.semana.sinUso.detalle": "Rien à projeter pour l'instant.",
  "proy.semana.sinDatos": "Il est trop tôt pour estimer",
  "proy.semana.sinDatos.detalle": "La semaine vient de commencer.",
  "proy.sinDatos": "Pas encore de données",
  "proy.sinDatos.detalle": "Attendez la première lecture.",
  "proy.nota": "Estimations selon votre rythme d'utilisation jusqu'ici.",

  // ----- Réglages -----
  "aj.seccion.vista": "Affichage",
  "aj.vista": "Vue",
  "aj.vista.normal": "Normale",
  "aj.vista.compacto": "Compacte (une seule ligne)",
  "aj.vista.completo": "Complète (tout à la fois)",
  "aj.disposicion": "Disposition",
  "aj.disposicion.vertical": "Verticale (barres empilées)",
  "aj.disposicion.horizontal": "Horizontale (côte à côte)",
  "aj.disposicion.ayuda": "S'applique à la vue normale ; la vue complète est toujours large.",
  "aj.seccion.escala": "Échelle de l'interface",
  "aj.escala.rapidos": "Tailles rapides",
  "aj.escala.ayuda": "Agrandit ou réduit tout instantanément. Aussi : Ctrl + molette (Ctrl 0 revient à 100 %).",
  "aj.seccion.apariencia": "Apparence",
  "aj.tema": "Thème",
  "aj.tema.oscuro": "Sombre",
  "aj.tema.claro": "Clair",
  "aj.tema.auto": "Automatique (comme Windows)",
  "aj.transparencia": "Transparence du fond",
  "aj.siempreEncima": "Toujours au-dessus des autres fenêtres",
  "aj.idioma": "Langue",
  "aj.idioma.auto": "Automatique (comme Windows)",
  "aj.seccion.limite": "Limite quotidienne",
  "aj.limite": "Limite",
  "aj.aviso": "Alerte préalable",
  "aj.limite.ayuda": "La part maximale de votre quota hebdomadaire à utiliser par jour. L'alerte doit être inférieure à la limite.",
  "aj.limitesPorDia": "Une limite différente pour chaque jour",
  "aj.limiteAuto": "Limite automatique",
  "aj.limiteAuto.ayuda": "Répartit ce qui reste de la semaine sur les jours jusqu’à la réinitialisation. Si vous utilisez peu un jour, vous avez plus les autres.",
  "aj.limiteAuto.hoy": "Aujourd’hui : {limite} %, ce qui reste de la semaine réparti sur les jours restants. L’alerte garde la même proportion.",
  "aj.limitesPorDia.ayuda": "L'alerte préalable s'ajuste toute seule, dans la même proportion.",
  "aj.dia.0": "Lu",
  "aj.dia.1": "Ma",
  "aj.dia.2": "Me",
  "aj.dia.3": "Je",
  "aj.dia.4": "Ve",
  "aj.dia.5": "Sa",
  "aj.dia.6": "Di",
  "aj.dia.aria": "Limite du {dia}",
  "aj.seccion.sesion": "Session de 5 heures",
  "aj.sesion.aviso": "M'alerter à",
  "aj.sesion.activar": "Activer les alertes de session",
  "aj.seccion.consulta": "Actualisation",
  "aj.intervalo": "Vérifier l'utilisation toutes les",
  "aj.intervalo.minutos": "{n} minutes",
  "aj.intervalo.hora": "1 heure",
  "aj.intervalo.ayuda": "Le minimum est de 5 minutes.",
  "aj.pausarOculto": "Ne pas vérifier quand le widget est masqué",
  "aj.pausarOculto.ayuda": "Tant qu’il est masqué, aucune alerte d’utilisation. Quand vous l’affichez, il se met à jour aussitôt.",
  "aj.seccion.sistema": "Système et données",
  "aj.arranque": "Ouvrir le widget au démarrage de Windows",
  "aj.exportar": "Exporter l'historique (CSV)…",
  "aj.guardar": "Enregistrer",
  "aj.guardado": "Enregistré ✓",
  "aj.exportado": "Terminé : {n} jour(s) enregistré(s).",

  // ----- Erreurs des réglages -----
  "err.limite": "La limite quotidienne doit être comprise entre 1 % et 100 %.",
  "err.avisoMinimo": "L'alerte préalable doit être d'au moins 1 %.",
  "err.avisoMenor": "L'alerte préalable doit être inférieure à la limite quotidienne.",
  "err.intervalo": "L'intervalle d'actualisation n'est pas valide.",
  "err.umbralSesion": "L'alerte de la session de 5 heures doit être comprise entre 50 % et 99 %.",
  "err.opcion": "Une option a une valeur non valide.",
  "err.vista": "La vue choisie n'est pas valide.",
  "err.disposicion": "La disposition choisie n'est pas valide.",
  "err.tema": "Le thème choisi n'est pas valide.",
  "err.idioma": "La langue choisie n'est pas valide.",
  "err.transparencia": "La transparence doit laisser le widget visible entre 40 % et 100 %.",
  "err.escala": "L'échelle doit être comprise entre {min} % et {max} %.",
  "err.limitesSiete": "Les limites par jour doivent être sept valeurs, du lundi au dimanche.",
  "err.limiteDia": "La limite de chaque jour doit être comprise entre 1 % et 100 %.",

  // ----- Menu de la zone de notification -----
  "tray.actualizado": "Headroom · mis à jour à {hora}",
  "tray.actualizar": "Actualiser",
  "tray.mostrarOcultar": "Afficher / Masquer",
  "tray.siempreEncima": "Toujours au-dessus",
  "tray.historial": "Historique",
  "boton.productos": "Utilisation par produit au fil du temps",
  "tray.productos": "Utilisation par produit",
  "historial.pocos": "Il se complète à chaque vérification (toutes les 5 minutes).",
  "panel.bienvenida": "Comment ça marche",
  "tray.bienvenida": "Comment ça marche",
  "bienvenida.hoy.titulo": "Aujourd’hui",
  "bienvenida.hoy": "Ce que vous avez utilisé aujourd’hui par rapport à votre limite du jour. Vous la choisissez dans les Réglages, ou elle se calcule toute seule.",
  "bienvenida.plan.titulo": "Session de 5 h et Semaine",
  "bienvenida.plan": "Les limites de votre forfait Claude, et le temps avant leur réinitialisation.",
  "bienvenida.clic.titulo": "Clic sur le nom d’une barre",
  "bienvenida.clic": "Ouvre le détail officiel sur claude.ai.",
  "bienvenida.cuentas.titulo": "Plusieurs comptes",
  "bienvenida.cuentas": "Cliquez sur l’étiquette avec le nom du compte, en haut à gauche.",
  "bienvenida.mover.titulo": "Le déplacer et le masquer",
  "bienvenida.mover": "Faites-le glisser où vous voulez. Ctrl + Alt + C le masque ou l’affiche.",
  "bienvenida.listo": "Compris",
  "tray.verEnClaude": "Voir l’utilisation sur claude.ai",
  "boton.verEnClaude": "Voir le détail sur claude.ai",
  "tray.desglose": "Répartition de la semaine",
  "tray.proyeccion": "Projection",
  "tray.vista": "Vue",
  "tray.vista.normal": "Normale",
  "tray.vista.compacto": "Compacte (une ligne)",
  "tray.vista.completo": "Complète (tout à la fois)",
  "tray.disposicion.vertical": "Disposition verticale",
  "tray.disposicion.horizontal": "Disposition horizontale",
  "tray.exportar": "Exporter l'historique (CSV)…",
  "tray.ajustes": "Réglages",
  "tray.cerrarSesion": "Se déconnecter",
  "tray.salir": "Quitter",

  // ----- Exporter l'historique -----
  "exportar.titulo": "Exporter l'historique d'utilisation",
  "exportar.filtro": "Fichier CSV (s'ouvre dans Excel)",
  "exportar.nombreArchivo": "historique-utilisation-claude-{fecha}.csv",
  "exportar.vacio": "Il n'y a pas encore de jours enregistrés à exporter.",
  "exportar.error": "Impossible d'enregistrer le fichier : {mensaje}",
  "csv.fecha": "Date",
  "csv.uso": "Utilisation du jour (%)",
  "csv.limite": "Limite du jour (%)",
  "csv.supero": "Limite dépassée ?",
  "csv.si": "Oui",
  "csv.no": "Non",

  // ----- Notifications Windows -----
  "alerta.limite.titulo": "Vous avez atteint votre limite quotidienne de Claude",
  "alerta.aviso.titulo": "Vous approchez de votre limite quotidienne de Claude",
  "alerta.diario.cuerpo": "Aujourd'hui vous avez utilisé {hoy} % de votre quota hebdomadaire (limite : {limite} %).",
  "alerta.sesionAviso.titulo": "Votre session de 5 heures touche à sa fin",
  "alerta.sesionAviso.cuerpo": "Vous avez utilisé {porcentaje} % de la session.",
  "alerta.sesionReinicia": " Elle se réinitialise à {hora}.",
  "alerta.sesionLimite.titulo": "Vous avez atteint la limite de la session de 5 heures",
  "alerta.sesionLimite.conHora": "Vous pourrez utiliser Claude à nouveau à {hora}.",
  "alerta.sesionLimite.sinHora": "Il faudra attendre la réinitialisation de la session.",
  "alerta.sesionReiniciada.titulo": "Votre session de 5 heures s'est réinitialisée",
  "alerta.sesionReiniciada.cuerpo": "Vous pouvez utiliser Claude à nouveau.",
  "alerta.exportado.titulo": "Historique exporté",
  "alerta.exportado.uno": "1 jour enregistré dans : {ruta}",
  "alerta.exportado.varios": "{n} jours enregistrés dans : {ruta}",
  "alerta.formato.titulo": "Le widget ne parvient pas à lire votre utilisation de Claude",
  "alerta.formato.cuerpo": "On dirait que claude.ai a changé sa page. Ouvrez Claude Code dans le dossier du projet et demandez-lui de vérifier src/uso.js.",

  // ----- Plusieurs comptes -----
  "cuentas.principal": "Principal",
  "login.tituloCuenta": "Se connecter à Claude — {nombre}",
  "panel.cuentas": "Comptes",
  "boton.cuenta": "Compte : {nombre} (cliquez pour voir, changer ou ajouter des comptes)",
  "cuentas.usar": "Afficher ce compte",
  "cuentas.nombre": "Nom du compte",
  "cuentas.estado.conectado": "Connecté",
  "cuentas.estado.sinSesion": "Non connecté",
  "cuentas.estado.expirada": "Session expirée",
  "cuentas.cerrarSesion": "Déconnexion",
  "cuentas.iniciarSesion": "Connexion",
  "cuentas.eliminar": "Supprimer ce compte",
  "cuentas.eliminarSeguro": "Sûr ?",
  "cuentas.nueva": "Nom (ex. : Travail)",
  "cuentas.agregar": "Ajouter",
  "tray.cuentaAgregar": "Ajouter un compte…",
  "cuentas.pasos": "1. Saisissez un nom pour le reconnaître (par exemple, Travail).\n2. Cliquez sur Ajouter.\n3. claude.ai s’ouvre : connectez-vous avec ce compte.",
  "cuentas.nuevaTitulo": "Ajouter un autre compte Claude",
  "cuentas.ayuda": "Se déconnecter garde l'historique et les limites : utile pour se connecter avec un autre compte Claude au même endroit. Supprimer efface tout.",
  "cuentas.err.nombre": "Saisissez un nom pour le compte.",
  "cuentas.err.maximo": "Vous pouvez avoir jusqu'à {n} comptes.",
  "aj.seccion.limiteDe": "Limite quotidienne · {nombre}",
  "resumen.sinSesion": "Non connecté",
  "tray.cuenta": "Compte",
  "tray.cuentasAdministrar": "Gérer les comptes…",
  "tray.cerrarSesionDe": "Déconnecter {nombre}",
  "aj.vista.cuentas": "Comptes (tous à la fois)",
  "aj.vista.mini": "Minimal (un cercle)",
  "tray.vista.mini": "Minimal (un cercle)",
  "mini.volver": "Cliquez pour revenir à la vue normale",
  "aj.todas": "Afficher tous les comptes à la fois",
  "aj.todas.ayuda": "Dans les vues normale et compacte, s'il y a plus d'un compte.",
  "aj.separadas": "Chaque compte dans sa propre fenêtre",
  "aj.separadas.ayuda": "Chacun se déplace séparément et a sa propre vue.",
  "tray.vista.cuentas": "Comptes (tous à la fois)",
  "boton.vistaNormal": "Revenir à la vue normale",
  "plan.free": "Gratuit",
  "plan.titulo": "Forfait {plan}",
  "extra.etiqueta": "Usage suppl.",
  "aj.seccion.semana": "Quota hebdomadaire",
  "aj.semana.aviso": "M'alerter à",
  "aj.semana.activar": "Activer l'alerte de la semaine",
  "err.umbralSemana": "L'alerte du quota hebdomadaire doit être comprise entre 50 % et 99 %.",
  "alerta.contexto.titulo": "Bon moment pour compacter",
  "alerta.contexto.cuerpo": "Le chat « {chat} » est à {porcentaje} % de son contexte. Tapez /compact dans Claude Code pour le résumer.",
  "aj.seccion.contexto": "Fenêtre de contexte de Claude Code",
  "chats.sinNombre": "Chat sans nom",
  "chats.titulo": "Fenêtre de contexte de Claude Code",
  "aj.contexto.mostrar": "Afficher le contexte de chaque chat",
  "aj.contexto.aviso": "M’avertir à",
  "aj.contexto.activar": "Me rappeler de compacter (et tous les 10 % de plus)",
  "aj.contexto.tamano": "Taille du contexte",
  "aj.contexto.auto": "Automatique",
  "aj.contexto.ayuda": "Ne fonctionne que si vous utilisez Claude Code sur cet ordinateur, et avec un seul compte dans Headroom. Ne voit pas les chats de claude.ai (web ou application) ni ceux d’autres ordinateurs. Affiche les chats des 3 dernières heures (jusqu’à 5).",
  "err.umbralContexto": "Le rappel du contexte doit être compris entre 10 % et 95 %.",
  "alerta.semanaAviso.titulo": "Votre quota hebdomadaire est élevé",
  "alerta.semanaAviso.cuerpo": "Vous avez utilisé {porcentaje} % du quota de la semaine.",
  "alerta.semanaAviso.reinicia": " Il se réinitialise {cuando}.",

  // ----- Améliorations : zone de notification, alertes, réinitialisation, couleurs, historique -----
  "tray.versionNueva": "Mettre à jour vers Headroom {version}",
  "tray.actualizando": "Téléchargement de la mise à jour… {progreso} %",
  "tray.silencio": "Désactiver les alertes",
  "tray.silencio.hasta": "Alertes désactivées jusqu'à {hora}",
  "tray.silencio.unaHora": "Pendant 1 heure",
  "tray.silencio.manana": "Jusqu'à demain",
  "tray.silencio.reactivar": "Réactiver les alertes",
  "alerta.version.titulo": "Une nouvelle version de Headroom est disponible",
  "alerta.version.cuerpo": "La version {version} est disponible. Cliquez pour mettre à jour.",
  "alerta.sesionRitmo.titulo": "À ce rythme, votre session sera épuisée",
  "alerta.sesionRitmo.cuerpo": "Vous atteindriez la limite vers {hora}, avant la réinitialisation à {reinicio}.",
  "err.colores": "Les couleurs choisies ne sont pas valides.",
  "tiempo.ahora": "maintenant",
  "tiempo.min": "dans {m} min",
  "tiempo.horas": "dans {h} h",
  "tiempo.horasMin": "dans {h} h {m} min",
  "tiempo.dias": "dans {d} j",
  "tiempo.diasHoras": "dans {d} j {h} h",
  "historial.7": "7 jours",
  "historial.dia": "Aujourd’hui",
  "historial.diaVacio": "Pas encore de relevés aujourd’hui. Le graphique se remplit à chaque vérification.",
  "historial.porDia": "Utilisation par jour",
  "historial.diasVacio": "Aucun jour enregistré pour l’instant. Le graphique se remplit jour après jour.",
  "historial.limite": "votre limite",
  "historial.30": "30 jours",
  "historial.dias": "Jours affichés",
  "historial.promedio": "Moyenne : {valor} % par jour",
  "aj.reinicio": "Afficher la réinitialisation",
  "aj.reinicio.relativo": "Compte à rebours (dans 2 h 15 min)",
  "aj.reinicio.hora": "Heure (15:06)",
  "aj.colores": "Couleurs",
  "aj.colores.acento": "Accent",
  "aj.colores.bajo": "Bas",
  "aj.colores.medio": "Moyen",
  "aj.colores.alto": "Élevé",
  "aj.colores.restablecer": "Rétablir",
  "aj.iconoDeColor": "Icône de notification colorée selon l'utilisation du jour",
  "aj.sesion.ritmo": "M'alerter si, à ce rythme, ma session va s'épuiser",
  "aj.atajo": "Ctrl + Alt + C affiche ou masque le widget",
  "aj.actualizaciones": "Me prévenir quand une nouvelle version sort",
  "aj.resumenes": "Résumé d’hier et de la semaine",
  "alerta.resumenDia.titulo": "Votre journée d’hier",
  "alerta.resumenDia.cuerpo": "Hier, vous avez utilisé {uso} % de votre quota hebdomadaire (votre limite était de {limite} %).",
  "alerta.resumenDia.pasado": "Hier, vous avez utilisé {uso} % de votre quota hebdomadaire : au-dessus de votre limite de {limite} %.",
  "alerta.resumenSemana.titulo": "Votre semaine est terminée",
  "alerta.resumenSemana.cuerpo": "Vous avez utilisé {semana} % de votre quota hebdomadaire.",
  "alerta.resumenSemana.dia": "Votre jour le plus élevé était {dia} ({uso} %).",
  "historial.horas": "Heures",
  "historial.horas.titulo": "À quelles heures de la journée vous l’utilisez le plus",
  "horas.pico": "Pic {desde}–{hasta} h",
  "horas.vacio": "Pas encore de données par heure : elles se remplissent à chaque jour d’utilisation.",
  "horas.dias": "Moyenne de {n} jour(s)",
  "comp.arriba": "Vous êtes {n} points au-dessus de la semaine dernière au même moment (vous étiez à {antes} %).",
  "comp.abajo": "Vous êtes {n} points en dessous de la semaine dernière au même moment (vous étiez à {antes} %).",
  "comp.igual": "Vous êtes à peu près au même niveau que la semaine dernière au même moment (vous étiez à {antes} %).",
  "comp.aprox": "C’est une estimation : elle sera exacte à partir de la semaine prochaine.",
  "comp.corto.arriba": "▲ {n} pts de plus que la semaine dernière",
  "comp.corto.abajo": "▼ {n} pts de moins que la semaine dernière",
  "comp.corto.igual": "= Comme la semaine dernière",
  "aj.copia.guardar": "Enregistrer une copie…",
  "aj.copia.restaurar": "Restaurer une copie…",
  "aj.copia.ayuda": "La copie conserve vos réglages, comptes et historique. Elle ne conserve pas vos sessions : sur un autre ordinateur, vous devrez vous reconnecter à chaque compte.",
  "copia.guardar.titulo": "Enregistrer une copie de sauvegarde",
  "copia.restaurar.titulo": "Restaurer une copie de sauvegarde",
  "copia.filtro": "Copie de Headroom",
  "copia.guardada": "Terminé : copie enregistrée.",
  "copia.invalida": "Ce fichier n’est pas une copie de Headroom.",
  "copia.confirmar": "Restaurer la copie du {fecha} ({n} compte(s)) ?",
  "copia.confirmar.detalle": "Vos réglages, comptes et historique actuels seront remplacés. Headroom va se fermer et se rouvrir.",
  "copia.confirmar.si": "Restaurer",
  "copia.confirmar.no": "Annuler",
  "aj.seccion.copia": "Sauvegarde",
  "productos.notaModelos": "En pointillé ({nombres}) : % de sa propre limite hebdomadaire.",
  "aj.seguirAClaude": "Afficher seulement quand Claude est ouvert",
  "aj.seguirAClaude.ayuda": "Il apparaît à l’ouverture de l’app Claude (ou de Claude Code) sur cet ordinateur et se masque à sa fermeture. Headroom reste dans la zone de notification ; il est utile d’activer aussi « Ouvrir le widget au démarrage de Windows ». Claude dans le navigateur n’est pas détecté.",
  "acerca.titulo": "À propos",
  "acerca.version": "Headroom {version} (installée)",
  "acerca.buscar": "Rechercher une mise à jour",
  "acerca.buscando": "Recherche…",
  "acerca.alDia": "Vous avez la dernière version.",
  "acerca.hayNueva": "Une nouvelle version est disponible : {version}.",
  "acerca.actualizar": "Mettre à jour vers la {version}",
  "acerca.descargando": "Téléchargement… Headroom va se fermer et se rouvrir.",
  "acerca.sinRespuesta": "Impossible de vérifier. Vérifiez votre connexion et réessayez plus tard.",
  "acerca.credito": "Créée par {autor} et Claude.",
  "comp.hoy.arriba": "Vous êtes {n} points au-dessus d’hier à la même heure (vous étiez à {antes} %).",
  "comp.hoy.abajo": "Vous êtes {n} points en dessous d’hier à la même heure (vous étiez à {antes} %).",
  "comp.hoy.igual": "Vous êtes à peu près au même niveau qu’hier à la même heure (vous étiez à {antes} %).",
  "comp.hoy.corto.arriba": "▲ {n} pts de plus qu’hier à cette heure",
  "comp.hoy.corto.abajo": "▼ {n} pts de moins qu’hier à cette heure",
  "comp.hoy.corto.igual": "= Comme hier à cette heure",
  "comp.sesion.arriba": "Vous êtes {n} points au-dessus de votre session précédente au même moment (vous étiez à {antes} %).",
  "comp.sesion.abajo": "Vous êtes {n} points en dessous de votre session précédente au même moment (vous étiez à {antes} %).",
  "comp.sesion.igual": "Vous êtes à peu près au même niveau que votre session précédente au même moment (vous étiez à {antes} %).",
  "comp.sesion.corto.arriba": "▲ {n} pts de plus que la session précédente",
  "comp.sesion.corto.abajo": "▼ {n} pts de moins que la session précédente",
  "comp.sesion.corto.igual": "= Comme la session précédente",
  "aj.vista.tablero": "Tableau de bord (tous les graphiques)",
  "tablero.titulo": "Tableau de bord",
  "tablero.hoy": "Aujourd’hui, heure par heure",
  "tablero.dias": "30 derniers jours",
  "tablero.horas": "Heures les plus chargées",
  "tablero.prodHoy": "Par produit : aujourd’hui",
  "tablero.prodSemana": "Par produit : cette semaine",
  "tablero.semanas": "Par produit : semaine par semaine",
  "tray.vista.tablero": "Tableau de bord (tous les graphiques)",
  "boton.tablero": "Tableau de bord (tous les graphiques)",
  "boton.mini": "Vue minimale (un cercle)",
};
