// pt.js: todos os textos do app em português (Brasil).
//
// Cada texto tem uma chave (ex. 'tray.salir'), as mesmas usadas em es.js. Os trechos entre chaves, como {hoy}, são
// substituídos por valores quando o texto é mostrado, então devem ficar exatamente como estão.

module.exports = {
  // ----- Dados do idioma -----
  "meta.nombre": "Português (Brasil)",
  "meta.locale": "pt-BR",
  "meta.csvSeparador": ";",

  // ----- Geral -----
  "app.nombre": "Headroom",
  "hoy.etiqueta": "Hoje",
  "sesion.etiqueta": "Sessão 5 h",
  "semana.etiqueta": "Semana",
  "reinicio.prefijo": "Reinicia: ",
  "hoy.de": "{hoy}% de {limite}%",
  "lectura.cargando": "Lendo o uso…",
  "sesion.sinActividad": "sem atividade",

  // ----- Erros ao ler o uso -----
  "error.sinConexion": "Sem conexão com claude.ai",
  "error.formato": "claude.ai mudou seus dados",
  "error.generico": "Não foi possível ler o uso",

  // ----- Login -----
  "login.sinSesion": "Você não entrou na sua conta",
  "login.expirada": "Sua sessão expirou",
  "login.iniciar": "Entrar",
  "login.reentrar": "Entrar de novo",
  "login.titulo": "Entrar no Claude",

  // ----- Painéis -----
  "panel.historial": "Histórico",
  "panel.desglose": "Detalhamento da semana",
  "panel.productos": "Uso por produto",
  "productos.ver": "Ao longo do tempo ›",
  "productos.semana": "Esta semana",
  "productos.semanas": "Semanas",
  "productos.estaSemana": "esta",
  "productos.semanasVacio": "Ainda não há semanas salvas. Cada vez que seu plano reinicia, uma é adicionada.",
  "productos.nota": "Em % da sua cota semanal: quanto cada produto usou.",
  "productos.vacio": "Ainda não há dias com o detalhe por produto. Vai se preenchendo dia a dia.",
  "panel.proyeccion": "Projeção",
  "panel.ajustes": "Configurações",
  "panel.detalle": "Detalhes",
  "panel.cerrar": "Fechar",
  "parte.separar": "Mover para uma janela própria",
  "parte.juntar": "Voltar ao widget",
  "parte.todas": "Todas as contas",
  "panel.cerrarAria": "Fechar o painel",

  // ----- Botões do cartão -----
  "boton.historial": "Histórico de uso",
  "boton.historialAria": "Ver o histórico de uso",
  "boton.desglose": "Detalhamento da semana por produto",
  "boton.desgloseAria": "Ver o detalhamento da semana por produto",
  "boton.proyeccion": "Projeção: neste ritmo...",
  "boton.proyeccionAria": "Ver a projeção de uso",
  "boton.ajustes": "Configurações",
  "boton.ajustesAria": "Abrir as configurações",
  "boton.compacto": "Visualização compacta (uma linha)",
  "boton.compactoAria": "Alternar entre a visualização compacta e a normal",
  "boton.completo": "Visualização completa (tudo de uma vez)",
  "boton.completoAria": "Alternar entre a visualização completa e a normal",
  "boton.orientacion": "Mudar a disposição (vertical / horizontal)",
  "boton.orientacionAria": "Alternar entre a disposição vertical e a horizontal",

  // ----- Histórico -----
  "historial.hoy": "hoje",
  "historial.limiteDia": "Limite desse dia: {limite}%",

  // ----- Nomes dos produtos -----
  "producto.claude_code": "Claude Code",
  "producto.chat": "Chats",
  "producto.cowork": "Cowork",
  "producto.other": "Outros",

  // ----- Detalhamento -----
  "desglose.sinDatos": "Ainda não há dados. Aguarde a primeira leitura.",
  "desglose.sinDesglose": "claude.ai não enviou o detalhamento nesta leitura.",
  "desglose.nota": "Divisão do que você usou nesta semana ({semana}% da sua cota).",
  "desglose.notaVarias": "Divisão do que cada conta usou nesta semana (à direita, sua % da cota).",

  // ----- Projeção -----
  "proy.dia.yaLlegaste": "Você já chegou ao limite de hoje",
  "proy.dia.yaLlegaste.detalle": "Melhor ir com calma pelo resto do dia.",
  "proy.dia.llegaras": "Você chegaria ao limite por volta das {hora}",
  "proy.dia.llegaras.detalle": "Neste ritmo, antes da meia-noite.",
  "proy.dia.noLlegaras": "Você não chegaria ao limite hoje",
  "proy.dia.noLlegaras.detalle": "Terminaria o dia com ~{fin}%.",
  "proy.dia.sinUso": "Você ainda não usou nada hoje",
  "proy.dia.sinUso.detalle": "Neste ritmo, não chegaria ao limite.",
  "proy.dia.sinDatos": "Ainda é cedo para estimar",
  "proy.dia.sinDatos.detalle": "Precisamos de pelo menos meia hora de medição.",
  "proy.semana.yaLlegaste": "Você esgotou sua cota semanal",
  "proy.semana.yaLlegaste.detalle": "Ela reinicia {reinicio}.",
  "proy.semana.llegaras": "Você chegaria a 100% na {cuando}",
  "proy.semana.llegaras.detalle": "Antes do reinício ({reinicio}).",
  "proy.semana.noLlegaras": "Você não esgotaria a cota esta semana",
  "proy.semana.noLlegaras.detalle": "Chegaria a ~{fin}% antes do reinício.",
  "proy.semana.sinUso": "Você ainda não usou nada esta semana",
  "proy.semana.sinUso.detalle": "Ainda não há o que projetar.",
  "proy.semana.sinDatos": "Ainda é cedo para estimar",
  "proy.semana.sinDatos.detalle": "A semana acabou de começar.",
  "proy.sinDatos": "Ainda sem dados",
  "proy.sinDatos.detalle": "Aguarde a primeira leitura.",
  "proy.nota": "Estimativas segundo o seu ritmo de uso até agora.",

  // ----- Configurações -----
  "aj.seccion.vista": "Visualização",
  "aj.vista": "Visualização",
  "aj.vista.normal": "Normal",
  "aj.vista.compacto": "Compacta (uma linha só)",
  "aj.vista.completo": "Completa (tudo de uma vez)",
  "aj.disposicion": "Disposição",
  "aj.disposicion.vertical": "Vertical (barras empilhadas)",
  "aj.disposicion.horizontal": "Horizontal (lado a lado)",
  "aj.disposicion.ayuda": "Vale para a visualização normal; a completa é sempre larga.",
  "aj.seccion.escala": "Escala da interface",
  "aj.escala.rapidos": "Tamanhos rápidos",
  "aj.escala.ayuda": "Aumenta ou diminui tudo na hora. Também: Ctrl + roda do mouse (Ctrl 0 volta a 100%).",
  "aj.seccion.apariencia": "Aparência",
  "aj.tema": "Tema",
  "aj.tema.oscuro": "Escuro",
  "aj.tema.claro": "Claro",
  "aj.tema.auto": "Automático (como o Windows)",
  "aj.transparencia": "Transparência do fundo",
  "aj.siempreEncima": "Sempre acima das outras janelas",
  "aj.idioma": "Idioma",
  "aj.idioma.auto": "Automático (como o Windows)",
  "aj.seccion.limite": "Limite diário",
  "aj.limite": "Limite",
  "aj.aviso": "Aviso prévio",
  "aj.limite.ayuda": "Quanto da sua cota semanal você quer usar no máximo por dia. O aviso deve ser menor que o limite.",
  "aj.limitesPorDia": "Um limite diferente para cada dia",
  "aj.limiteAuto": "Limite automático",
  "aj.limiteAuto.ayuda": "Divide o que resta da semana entre os dias que faltam para o reinício. Se num dia você usa pouco, nos outros sobra mais.",
  "aj.limiteAuto.hoy": "Hoje você tem {limite}%: o que resta da semana dividido pelos dias que faltam. O aviso mantém a mesma proporção.",
  "aj.limitesPorDia.ayuda": "O aviso prévio se ajusta sozinho, na mesma proporção.",
  "aj.dia.0": "Seg",
  "aj.dia.1": "Ter",
  "aj.dia.2": "Qua",
  "aj.dia.3": "Qui",
  "aj.dia.4": "Sex",
  "aj.dia.5": "Sáb",
  "aj.dia.6": "Dom",
  "aj.dia.aria": "Limite de {dia}",
  "aj.seccion.sesion": "Sessão de 5 horas",
  "aj.sesion.aviso": "Avisar ao chegar a",
  "aj.sesion.activar": "Ativar os avisos da sessão",
  "aj.seccion.consulta": "Consulta",
  "aj.intervalo": "Consultar o uso a cada",
  "aj.intervalo.minutos": "{n} minutos",
  "aj.intervalo.hora": "1 hora",
  "aj.intervalo.ayuda": "O mínimo é 5 minutos.",
  "aj.pausarOculto": "Não consultar enquanto o widget estiver oculto",
  "aj.pausarOculto.ayuda": "Enquanto estiver oculto não há avisos de uso. Ao mostrá-lo, ele se atualiza na hora.",
  "aj.seccion.sistema": "Sistema e dados",
  "aj.arranque": "Abrir o widget ao iniciar o Windows",
  "aj.exportar": "Exportar histórico (CSV)…",
  "aj.guardar": "Salvar",
  "aj.guardado": "Salvo ✓",
  "aj.exportado": "Pronto: {n} dia(s) salvos.",

  // ----- Erros das configurações -----
  "err.limite": "O limite diário deve estar entre 1% e 100%.",
  "err.avisoMinimo": "O aviso prévio deve ser de pelo menos 1%.",
  "err.avisoMenor": "O aviso prévio deve ser menor que o limite diário.",
  "err.intervalo": "O intervalo de consulta não é válido.",
  "err.umbralSesion": "O aviso da sessão de 5 horas deve estar entre 50% e 99%.",
  "err.opcion": "Uma opção tem um valor inválido.",
  "err.vista": "A visualização escolhida não é válida.",
  "err.disposicion": "A disposição escolhida não é válida.",
  "err.tema": "O tema escolhido não é válido.",
  "err.idioma": "O idioma escolhido não é válido.",
  "err.transparencia": "A transparência deve deixar o widget entre 40% e 100% visível.",
  "err.escala": "A escala deve estar entre {min}% e {max}%.",
  "err.limitesSiete": "Os limites por dia devem ser sete valores, de segunda a domingo.",
  "err.limiteDia": "O limite de cada dia deve estar entre 1% e 100%.",

  // ----- Menu da bandeja (ao lado do relógio) -----
  "tray.actualizado": "Headroom · atualizado {hora}",
  "tray.actualizar": "Atualizar",
  "tray.mostrarOcultar": "Mostrar / Ocultar",
  "tray.siempreEncima": "Sempre acima",
  "tray.historial": "Histórico",
  "boton.productos": "Uso por produto ao longo do tempo",
  "tray.productos": "Uso por produto",
  "historial.pocos": "Vai se desenhando a cada consulta (a cada 5 minutos).",
  "panel.bienvenida": "Como funciona",
  "tray.bienvenida": "Como funciona",
  "bienvenida.hoy.titulo": "Hoje",
  "bienvenida.hoy": "O que você usou hoje em relação ao seu limite diário. Você escolhe o limite em Configurações, ou deixa que seja calculado sozinho.",
  "bienvenida.plan.titulo": "Sessão de 5 h e Semana",
  "bienvenida.plan": "Os limites do seu plano do Claude, e quanto falta para reiniciarem.",
  "bienvenida.clic.titulo": "Clique no nome de uma barra",
  "bienvenida.clic": "Abre o detalhe oficial no claude.ai.",
  "bienvenida.cuentas.titulo": "Várias contas",
  "bienvenida.cuentas": "Clique na etiqueta com o nome da conta, no canto superior esquerdo.",
  "bienvenida.mover.titulo": "Mover e ocultar",
  "bienvenida.mover": "Arraste para onde quiser. Ctrl + Alt + C oculta ou mostra.",
  "bienvenida.listo": "Entendi",
  "tray.verEnClaude": "Ver o uso no claude.ai",
  "boton.verEnClaude": "Ver o detalhe no claude.ai",
  "tray.desglose": "Detalhamento da semana",
  "tray.proyeccion": "Projeção",
  "tray.vista": "Visualização",
  "tray.vista.normal": "Normal",
  "tray.vista.compacto": "Compacta (uma linha)",
  "tray.vista.completo": "Completa (tudo de uma vez)",
  "tray.disposicion.vertical": "Disposição vertical",
  "tray.disposicion.horizontal": "Disposição horizontal",
  "tray.exportar": "Exportar histórico (CSV)…",
  "tray.ajustes": "Configurações",
  "tray.cerrarSesion": "Sair da conta",
  "tray.salir": "Sair",

  // ----- Exportar o histórico -----
  "exportar.titulo": "Exportar histórico de uso",
  "exportar.filtro": "Arquivo CSV (abre no Excel)",
  "exportar.nombreArchivo": "historico-uso-claude-{fecha}.csv",
  "exportar.vacio": "Ainda não há dias registrados para exportar.",
  "exportar.error": "Não foi possível salvar o arquivo: {mensaje}",
  "csv.fecha": "Data",
  "csv.uso": "Uso do dia (%)",
  "csv.limite": "Limite do dia (%)",
  "csv.supero": "Passou do limite?",
  "csv.si": "Sim",
  "csv.no": "Não",

  // ----- Notificações do Windows -----
  "alerta.limite.titulo": "Você chegou ao seu limite diário do Claude",
  "alerta.aviso.titulo": "Você está perto do seu limite diário do Claude",
  "alerta.diario.cuerpo": "Hoje você usou {hoy}% da sua cota semanal (limite: {limite}%).",
  "alerta.sesionAviso.titulo": "Sua sessão de 5 horas está acabando",
  "alerta.sesionAviso.cuerpo": "Você já usou {porcentaje}% da sessão.",
  "alerta.sesionReinicia": " Ela reinicia às {hora}.",
  "alerta.sesionLimite.titulo": "Você chegou ao limite da sessão de 5 horas",
  "alerta.sesionLimite.conHora": "Você poderá usar o Claude de novo às {hora}.",
  "alerta.sesionLimite.sinHora": "Será preciso esperar a sessão reiniciar.",
  "alerta.sesionReiniciada.titulo": "Sua sessão de 5 horas reiniciou",
  "alerta.sesionReiniciada.cuerpo": "Você já pode usar o Claude de novo.",
  "alerta.exportado.titulo": "Histórico exportado",
  "alerta.exportado.uno": "1 dia salvo em: {ruta}",
  "alerta.exportado.varios": "{n} dias salvos em: {ruta}",
  "alerta.formato.titulo": "O widget não consegue ler seu uso do Claude",
  "alerta.formato.cuerpo": "Parece que claude.ai mudou a página. Abra o Claude Code na pasta do projeto e peça para revisar src/uso.js.",

  // ----- Várias contas -----
  "cuentas.principal": "Principal",
  "login.tituloCuenta": "Entrar no Claude — {nombre}",
  "panel.cuentas": "Contas",
  "boton.cuenta": "Conta: {nombre} (clique para ver, trocar ou adicionar contas)",
  "cuentas.usar": "Mostrar esta conta",
  "cuentas.nombre": "Nome da conta",
  "cuentas.estado.conectado": "Conectada",
  "cuentas.estado.sinSesion": "Sem sessão",
  "cuentas.estado.expirada": "Sessão expirada",
  "cuentas.cerrarSesion": "Sair",
  "cuentas.iniciarSesion": "Entrar",
  "cuentas.eliminar": "Excluir esta conta",
  "cuentas.eliminarSeguro": "Certeza?",
  "cuentas.nueva": "Nome (ex.: Trabalho)",
  "cuentas.agregar": "Adicionar",
  "tray.cuentaAgregar": "Adicionar conta…",
  "cuentas.pasos": "1. Digite um nome para reconhecê-la (por exemplo, Trabalho).\n2. Clique em Adicionar.\n3. O claude.ai abre: entre com essa conta.",
  "cuentas.nuevaTitulo": "Adicionar outra conta do Claude",
  "cuentas.ayuda": "Sair mantém o histórico e os limites: serve para entrar com outra conta do Claude no mesmo lugar. Excluir apaga tudo.",
  "cuentas.err.nombre": "Escreva um nome para a conta.",
  "cuentas.err.maximo": "Você pode ter até {n} contas.",
  "aj.seccion.limiteDe": "Limite diário · {nombre}",
  "resumen.sinSesion": "Sem sessão",
  "tray.cuenta": "Conta",
  "tray.cuentasAdministrar": "Gerenciar contas…",
  "tray.cerrarSesionDe": "Sair de {nombre}",
  "aj.vista.cuentas": "Contas (todas de uma vez)",
  "aj.vista.mini": "Mínimo (um círculo)",
  "tray.vista.mini": "Mínimo (um círculo)",
  "mini.volver": "Clique para voltar à visualização normal",
  "aj.todas": "Mostrar todas as contas de uma vez",
  "aj.todas.ayuda": "Nas visualizações normal e compacta, se houver mais de uma conta.",
  "aj.separadas": "Cada conta em sua própria janela",
  "aj.separadas.ayuda": "Cada uma se move separadamente e tem sua própria visualização.",
  "tray.vista.cuentas": "Contas (todas de uma vez)",
  "boton.vistaNormal": "Voltar à visualização normal",
  "plan.free": "Grátis",
  "plan.titulo": "Plano {plan}",
  "extra.etiqueta": "Uso extra",
  "aj.seccion.semana": "Cota semanal",
  "aj.semana.aviso": "Avisar ao chegar a",
  "aj.semana.activar": "Ativar o aviso da semana",
  "err.umbralSemana": "O aviso da cota semanal deve estar entre 50% e 99%.",
  "alerta.contexto.titulo": "Bom momento para compactar",
  "alerta.contexto.cuerpo": "O chat “{chat}” está em {porcentaje}% do contexto. Digite /compact no Claude Code para resumi-lo.",
  "aj.seccion.contexto": "Janela de contexto do Claude Code",
  "chats.sinNombre": "Chat sem nome",
  "chats.titulo": "Janela de contexto do Claude Code",
  "aj.contexto.mostrar": "Mostrar o contexto de cada chat",
  "aj.contexto.aviso": "Avisar ao chegar a",
  "aj.contexto.activar": "Lembrar de compactar (e a cada 10% a mais)",
  "aj.contexto.tamano": "Tamanho do contexto",
  "aj.contexto.auto": "Automático",
  "aj.contexto.ayuda": "Só funciona se você usa o Claude Code neste mesmo computador, e só com uma conta no Headroom. Não vê os chats do claude.ai (na web ou no app) nem os de outros computadores. Mostra os chats das últimas 3 horas (até 5).",
  "err.umbralContexto": "O lembrete do contexto deve estar entre 10% e 95%.",
  "alerta.semanaAviso.titulo": "Sua cota semanal está alta",
  "alerta.semanaAviso.cuerpo": "Você já usou {porcentaje}% da cota da semana.",
  "alerta.semanaAviso.reinicia": " Ela reinicia {cuando}.",

  // ----- Melhorias: bandeja, avisos, reinício, cores, histórico -----
  "tray.versionNueva": "Atualizar para o Headroom {version}",
  "tray.actualizando": "Baixando a atualização… {progreso}%",
  "tray.silencio": "Silenciar avisos",
  "tray.silencio.hasta": "Avisos silenciados até {hora}",
  "tray.silencio.unaHora": "Por 1 hora",
  "tray.silencio.manana": "Até amanhã",
  "tray.silencio.reactivar": "Reativar os avisos",
  "alerta.version.titulo": "Há uma nova versão do Headroom",
  "alerta.version.cuerpo": "A versão {version} está disponível. Clique para atualizar.",
  "alerta.sesionRitmo.titulo": "Neste ritmo sua sessão vai acabar",
  "alerta.sesionRitmo.cuerpo": "Você chegaria ao limite por volta das {hora}, antes do reinício às {reinicio}.",
  "err.colores": "As cores escolhidas não são válidas.",
  "tiempo.ahora": "agora",
  "tiempo.min": "em {m} min",
  "tiempo.horas": "em {h} h",
  "tiempo.horasMin": "em {h} h {m} min",
  "tiempo.dias": "em {d} d",
  "tiempo.diasHoras": "em {d} d {h} h",
  "historial.7": "7 dias",
  "historial.dia": "Hoje",
  "historial.diaVacio": "Ainda não há leituras de hoje. O gráfico vai se preenchendo a cada consulta.",
  "historial.porDia": "Uso por dia",
  "historial.diasVacio": "Ainda não há dias salvos. O gráfico vai se preenchendo dia a dia.",
  "historial.limite": "seu limite",
  "historial.30": "30 dias",
  "historial.dias": "Dias mostrados",
  "historial.promedio": "Média: {valor}% por dia",
  "aj.reinicio": "Mostrar o reinício como",
  "aj.reinicio.relativo": "Contagem regressiva (em 2 h 15 min)",
  "aj.reinicio.hora": "Hora (15:06)",
  "aj.colores": "Cores",
  "aj.colores.acento": "Destaque",
  "aj.colores.bajo": "Baixo",
  "aj.colores.medio": "Médio",
  "aj.colores.alto": "Alto",
  "aj.colores.restablecer": "Restaurar",
  "aj.iconoDeColor": "Ícone da bandeja com a cor do uso de hoje",
  "aj.sesion.ritmo": "Avisar se neste ritmo a sessão vai acabar",
  "aj.atajo": "Ctrl + Alt + C mostra ou oculta o widget",
  "aj.actualizaciones": "Avisar quando houver uma nova versão",
  "aj.resumenes": "Resumo de ontem e da semana",
  "alerta.resumenDia.titulo": "Seu dia de ontem",
  "alerta.resumenDia.cuerpo": "Ontem você usou {uso}% da sua cota semanal (seu limite era {limite}%).",
  "alerta.resumenDia.pasado": "Ontem você usou {uso}% da sua cota semanal: passou do seu limite de {limite}%.",
  "alerta.resumenSemana.titulo": "Sua semana terminou",
  "alerta.resumenSemana.cuerpo": "Você usou {semana}% da sua cota semanal.",
  "alerta.resumenSemana.dia": "Seu dia mais alto foi {dia} ({uso}%).",
  "historial.horas": "Horas",
  "historial.horas.titulo": "Em que horas do dia você usa mais",
  "horas.pico": "Pico {desde}–{hasta} h",
  "horas.vacio": "Ainda não há dados por hora: vai preenchendo a cada dia de uso.",
  "horas.dias": "Média de {n} dia(s)",
  "comp.arriba": "Você está {n} pontos acima da semana passada nesta mesma altura (estava em {antes}%).",
  "comp.abajo": "Você está {n} pontos abaixo da semana passada nesta mesma altura (estava em {antes}%).",
  "comp.igual": "Você está quase igual à semana passada nesta mesma altura (estava em {antes}%).",
  "comp.aprox": "É uma estimativa: será exata a partir da próxima semana.",
  "comp.corto.arriba": "▲ {n} pts a mais que na semana passada",
  "comp.corto.abajo": "▼ {n} pts a menos que na semana passada",
  "comp.corto.igual": "= Igual à semana passada",
  "aj.copia.guardar": "Salvar cópia…",
  "aj.copia.restaurar": "Restaurar cópia…",
  "aj.copia.ayuda": "A cópia guarda seus ajustes, contas e histórico. Não guarda suas sessões: em outro computador você terá que entrar de novo em cada conta.",
  "copia.guardar.titulo": "Salvar cópia de segurança",
  "copia.restaurar.titulo": "Restaurar cópia de segurança",
  "copia.filtro": "Cópia do Headroom",
  "copia.guardada": "Pronto: cópia salva.",
  "copia.invalida": "Esse arquivo não é uma cópia do Headroom.",
  "copia.confirmar": "Restaurar a cópia de {fecha} ({n} conta(s))?",
  "copia.confirmar.detalle": "Seus ajustes, contas e histórico atuais serão substituídos. O Headroom será fechado e aberto novamente.",
  "copia.confirmar.si": "Restaurar",
  "copia.confirmar.no": "Cancelar",
  "aj.seccion.copia": "Cópia de segurança",
};
